-- Extensions the schema depends on.
--
-- citext  — case-insensitive text, used for users.email so "Ana@x.com" and "ana@x.com"
--           cannot become two accounts. Doing this with lower() indexes instead would put
--           the rule in every query rather than in the column.
-- pgcrypto — gen_random_uuid() as a server-side fallback. Ids are normally generated by
--           the client (SPEC.md section 7), but a default keeps direct SQL inserts and
--           seeds honest.

CREATE EXTENSION IF NOT EXISTS citext;
CREATE EXTENSION IF NOT EXISTS pgcrypto;
