// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: obligations.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createObligation = `-- name: CreateObligation :one
INSERT INTO vehicle_obligations (
    id, vehicle_id, kind, reference_year, due_on, amount_cents,
    paid_on, paid_amount_cents, notes, recorded_by_user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (vehicle_id, kind, reference_year) DO NOTHING
RETURNING id, vehicle_id, kind, reference_year, due_on, amount_cents, paid_on, paid_amount_cents, notes, recorded_by_user_id, created_at, updated_at
`

type CreateObligationParams struct {
	ID               uuid.UUID
	VehicleID        uuid.UUID
	Kind             string
	ReferenceYear    int32
	DueOn            time.Time
	AmountCents      *int64
	PaidOn           *time.Time
	PaidAmountCents  *int64
	Notes            *string
	RecordedByUserID *uuid.UUID
}

func (q *Queries) CreateObligation(ctx context.Context, arg CreateObligationParams) (VehicleObligation, error) {
	row := q.db.QueryRow(ctx, createObligation,
		arg.ID,
		arg.VehicleID,
		arg.Kind,
		arg.ReferenceYear,
		arg.DueOn,
		arg.AmountCents,
		arg.PaidOn,
		arg.PaidAmountCents,
		arg.Notes,
		arg.RecordedByUserID,
	)
	var i VehicleObligation
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Kind,
		&i.ReferenceYear,
		&i.DueOn,
		&i.AmountCents,
		&i.PaidOn,
		&i.PaidAmountCents,
		&i.Notes,
		&i.RecordedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteObligation = `-- name: DeleteObligation :execrows
DELETE FROM vehicle_obligations WHERE id = $1
`

// Hard delete: an obligation is the owner's private record, not vehicle history that
// travels on resale (SPEC.md RN-10).
func (q *Queries) DeleteObligation(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteObligation, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getObligationForUser = `-- name: GetObligationForUser :one
SELECT o.id, o.vehicle_id, o.kind, o.reference_year, o.due_on, o.amount_cents, o.paid_on, o.paid_amount_cents, o.notes, o.recorded_by_user_id, o.created_at, o.updated_at
FROM vehicle_obligations o
JOIN vehicle_ownerships vo ON vo.vehicle_id = o.vehicle_id
WHERE o.id = $1
  AND vo.user_id = $2
  AND vo.ended_on IS NULL
`

type GetObligationForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Read through ownership, never by id alone (SPEC.md RN-07). The join is the
// authorisation.
func (q *Queries) GetObligationForUser(ctx context.Context, arg GetObligationForUserParams) (VehicleObligation, error) {
	row := q.db.QueryRow(ctx, getObligationForUser, arg.ID, arg.UserID)
	var i VehicleObligation
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Kind,
		&i.ReferenceYear,
		&i.DueOn,
		&i.AmountCents,
		&i.PaidOn,
		&i.PaidAmountCents,
		&i.Notes,
		&i.RecordedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listObligationsForVehicle = `-- name: ListObligationsForVehicle :many
SELECT id, vehicle_id, kind, reference_year, due_on, amount_cents, paid_on, paid_amount_cents, notes, recorded_by_user_id, created_at, updated_at
FROM vehicle_obligations
WHERE vehicle_id = $1
  AND ($2::text IS NULL OR kind = $2)
ORDER BY due_on DESC
`

type ListObligationsForVehicleParams struct {
	VehicleID uuid.UUID
	Kind      *string
}

func (q *Queries) ListObligationsForVehicle(ctx context.Context, arg ListObligationsForVehicleParams) ([]VehicleObligation, error) {
	rows, err := q.db.Query(ctx, listObligationsForVehicle, arg.VehicleID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VehicleObligation{}
	for rows.Next() {
		var i VehicleObligation
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.Kind,
			&i.ReferenceYear,
			&i.DueOn,
			&i.AmountCents,
			&i.PaidOn,
			&i.PaidAmountCents,
			&i.Notes,
			&i.RecordedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateObligation = `-- name: UpdateObligation :one
UPDATE vehicle_obligations
SET due_on            = COALESCE($1, due_on),
    amount_cents      = COALESCE($2, amount_cents),
    paid_on           = CASE WHEN $3::boolean THEN NULL
                             ELSE COALESCE($4, paid_on) END,
    paid_amount_cents = CASE WHEN $3::boolean THEN NULL
                             ELSE COALESCE($5, paid_amount_cents) END,
    notes             = COALESCE($6, notes),
    updated_at        = now()
WHERE id = $7
RETURNING id, vehicle_id, kind, reference_year, due_on, amount_cents, paid_on, paid_amount_cents, notes, recorded_by_user_id, created_at, updated_at
`

type UpdateObligationParams struct {
	DueOn           *time.Time
	AmountCents     *int64
	ClearPayment    bool
	PaidOn          *time.Time
	PaidAmountCents *int64
	Notes           *string
	ID              uuid.UUID
}

// PATCH semantics: a NULL argument leaves the column alone.
//
// Marking an obligation unpaid needs its own flag, because NULL already means "unchanged"
// and undoing a mistaken "paid" is a thing people do.
func (q *Queries) UpdateObligation(ctx context.Context, arg UpdateObligationParams) (VehicleObligation, error) {
	row := q.db.QueryRow(ctx, updateObligation,
		arg.DueOn,
		arg.AmountCents,
		arg.ClearPayment,
		arg.PaidOn,
		arg.PaidAmountCents,
		arg.Notes,
		arg.ID,
	)
	var i VehicleObligation
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.Kind,
		&i.ReferenceYear,
		&i.DueOn,
		&i.AmountCents,
		&i.PaidOn,
		&i.PaidAmountCents,
		&i.Notes,
		&i.RecordedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
