// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: seguros.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createSeguro = `-- name: CreateSeguro :one
INSERT INTO seguros (
    id, vehicle_id, insurer_name, policy_number, starts_on, ends_on,
    premium_cents, emergency_phone, broker_name, broker_phone, notes,
    recorded_by_user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
ON CONFLICT (id) DO NOTHING
RETURNING id, vehicle_id, insurer_name, policy_number, starts_on, ends_on, premium_cents, emergency_phone, broker_name, broker_phone, notes, recorded_by_user_id, created_at, updated_at
`

type CreateSeguroParams struct {
	ID               uuid.UUID
	VehicleID        uuid.UUID
	InsurerName      string
	PolicyNumber     *string
	StartsOn         time.Time
	EndsOn           time.Time
	PremiumCents     *int64
	EmergencyPhone   *string
	BrokerName       *string
	BrokerPhone      *string
	Notes            *string
	RecordedByUserID *uuid.UUID
}

func (q *Queries) CreateSeguro(ctx context.Context, arg CreateSeguroParams) (Seguro, error) {
	row := q.db.QueryRow(ctx, createSeguro,
		arg.ID,
		arg.VehicleID,
		arg.InsurerName,
		arg.PolicyNumber,
		arg.StartsOn,
		arg.EndsOn,
		arg.PremiumCents,
		arg.EmergencyPhone,
		arg.BrokerName,
		arg.BrokerPhone,
		arg.Notes,
		arg.RecordedByUserID,
	)
	var i Seguro
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.InsurerName,
		&i.PolicyNumber,
		&i.StartsOn,
		&i.EndsOn,
		&i.PremiumCents,
		&i.EmergencyPhone,
		&i.BrokerName,
		&i.BrokerPhone,
		&i.Notes,
		&i.RecordedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSeguro = `-- name: DeleteSeguro :execrows
DELETE FROM seguros WHERE id = $1
`

// Hard delete: a policy is the owner's private record — insurer, broker and phone numbers
// are exactly what must NOT travel with the vehicle on resale (SPEC.md RN-10).
func (q *Queries) DeleteSeguro(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteSeguro, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getSeguroByID = `-- name: GetSeguroByID :one
SELECT id, vehicle_id, insurer_name, policy_number, starts_on, ends_on, premium_cents, emergency_phone, broker_name, broker_phone, notes, recorded_by_user_id, created_at, updated_at FROM seguros WHERE id = $1
`

func (q *Queries) GetSeguroByID(ctx context.Context, id uuid.UUID) (Seguro, error) {
	row := q.db.QueryRow(ctx, getSeguroByID, id)
	var i Seguro
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.InsurerName,
		&i.PolicyNumber,
		&i.StartsOn,
		&i.EndsOn,
		&i.PremiumCents,
		&i.EmergencyPhone,
		&i.BrokerName,
		&i.BrokerPhone,
		&i.Notes,
		&i.RecordedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSeguroForUser = `-- name: GetSeguroForUser :one
SELECT s.id, s.vehicle_id, s.insurer_name, s.policy_number, s.starts_on, s.ends_on, s.premium_cents, s.emergency_phone, s.broker_name, s.broker_phone, s.notes, s.recorded_by_user_id, s.created_at, s.updated_at
FROM seguros s
JOIN vehicle_ownerships vo ON vo.vehicle_id = s.vehicle_id
WHERE s.id = $1
  AND vo.user_id = $2
  AND vo.ended_on IS NULL
`

type GetSeguroForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

func (q *Queries) GetSeguroForUser(ctx context.Context, arg GetSeguroForUserParams) (Seguro, error) {
	row := q.db.QueryRow(ctx, getSeguroForUser, arg.ID, arg.UserID)
	var i Seguro
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.InsurerName,
		&i.PolicyNumber,
		&i.StartsOn,
		&i.EndsOn,
		&i.PremiumCents,
		&i.EmergencyPhone,
		&i.BrokerName,
		&i.BrokerPhone,
		&i.Notes,
		&i.RecordedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSegurosForVehicle = `-- name: ListSegurosForVehicle :many
SELECT id, vehicle_id, insurer_name, policy_number, starts_on, ends_on, premium_cents, emergency_phone, broker_name, broker_phone, notes, recorded_by_user_id, created_at, updated_at FROM seguros
WHERE vehicle_id = $1
ORDER BY ends_on DESC
`

// Newest period first: the current policy is what the owner opens the screen for.
func (q *Queries) ListSegurosForVehicle(ctx context.Context, vehicleID uuid.UUID) ([]Seguro, error) {
	rows, err := q.db.Query(ctx, listSegurosForVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Seguro{}
	for rows.Next() {
		var i Seguro
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.InsurerName,
			&i.PolicyNumber,
			&i.StartsOn,
			&i.EndsOn,
			&i.PremiumCents,
			&i.EmergencyPhone,
			&i.BrokerName,
			&i.BrokerPhone,
			&i.Notes,
			&i.RecordedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSeguro = `-- name: UpdateSeguro :one
UPDATE seguros
SET insurer_name    = COALESCE($1, insurer_name),
    policy_number   = COALESCE($2, policy_number),
    starts_on       = COALESCE($3, starts_on),
    ends_on         = COALESCE($4, ends_on),
    premium_cents   = COALESCE($5, premium_cents),
    emergency_phone = COALESCE($6, emergency_phone),
    broker_name     = COALESCE($7, broker_name),
    broker_phone    = COALESCE($8, broker_phone),
    notes           = COALESCE($9, notes),
    updated_at      = now()
WHERE id = $10
RETURNING id, vehicle_id, insurer_name, policy_number, starts_on, ends_on, premium_cents, emergency_phone, broker_name, broker_phone, notes, recorded_by_user_id, created_at, updated_at
`

type UpdateSeguroParams struct {
	InsurerName    *string
	PolicyNumber   *string
	StartsOn       *time.Time
	EndsOn         *time.Time
	PremiumCents   *int64
	EmergencyPhone *string
	BrokerName     *string
	BrokerPhone    *string
	Notes          *string
	ID             uuid.UUID
}

func (q *Queries) UpdateSeguro(ctx context.Context, arg UpdateSeguroParams) (Seguro, error) {
	row := q.db.QueryRow(ctx, updateSeguro,
		arg.InsurerName,
		arg.PolicyNumber,
		arg.StartsOn,
		arg.EndsOn,
		arg.PremiumCents,
		arg.EmergencyPhone,
		arg.BrokerName,
		arg.BrokerPhone,
		arg.Notes,
		arg.ID,
	)
	var i Seguro
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.InsurerName,
		&i.PolicyNumber,
		&i.StartsOn,
		&i.EndsOn,
		&i.PremiumCents,
		&i.EmergencyPhone,
		&i.BrokerName,
		&i.BrokerPhone,
		&i.Notes,
		&i.RecordedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
