// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (id, email, password_hash, name)
VALUES ($1, $2, $3, $4)
RETURNING id, email, password_hash, name, created_at, updated_at, birth_date, phone, cnh_category, cnh_expires_on, photo_key
`

type CreateUserParams struct {
	ID           uuid.UUID
	Email        string
	PasswordHash string
	Name         string
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.PasswordHash,
		arg.Name,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BirthDate,
		&i.Phone,
		&i.CnhCategory,
		&i.CnhExpiresOn,
		&i.PhotoKey,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :execrows
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteUser, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, password_hash, name, created_at, updated_at, birth_date, phone, cnh_category, cnh_expires_on, photo_key FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BirthDate,
		&i.Phone,
		&i.CnhCategory,
		&i.CnhExpiresOn,
		&i.PhotoKey,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, password_hash, name, created_at, updated_at, birth_date, phone, cnh_category, cnh_expires_on, photo_key FROM users WHERE id = $1
`

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BirthDate,
		&i.Phone,
		&i.CnhCategory,
		&i.CnhExpiresOn,
		&i.PhotoKey,
	)
	return i, err
}

const lockUserPhotoKey = `-- name: LockUserPhotoKey :one
SELECT photo_key FROM users WHERE id = $1 FOR UPDATE
`

// Reads the photo a user has now, locking the row so a concurrent upload waits and then
// sees this one's key. Called inside the transaction that sets the new one.
func (q *Queries) LockUserPhotoKey(ctx context.Context, id uuid.UUID) (*string, error) {
	row := q.db.QueryRow(ctx, lockUserPhotoKey, id)
	var photo_key *string
	err := row.Scan(&photo_key)
	return photo_key, err
}

const setUserPhotoKey = `-- name: SetUserPhotoKey :one
UPDATE users
SET photo_key  = $1,
    updated_at = now()
WHERE id = $2
RETURNING id, email, password_hash, name, created_at, updated_at, birth_date, phone, cnh_category, cnh_expires_on, photo_key
`

type SetUserPhotoKeyParams struct {
	PhotoKey *string
	ID       uuid.UUID
}

func (q *Queries) SetUserPhotoKey(ctx context.Context, arg SetUserPhotoKeyParams) (User, error) {
	row := q.db.QueryRow(ctx, setUserPhotoKey, arg.PhotoKey, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BirthDate,
		&i.Phone,
		&i.CnhCategory,
		&i.CnhExpiresOn,
		&i.PhotoKey,
	)
	return i, err
}

const updateUserPassword = `-- name: UpdateUserPassword :execrows
UPDATE users
SET password_hash = $2, updated_at = now()
WHERE id = $1
`

type UpdateUserPasswordParams struct {
	ID           uuid.UUID
	PasswordHash string
}

func (q *Queries) UpdateUserPassword(ctx context.Context, arg UpdateUserPasswordParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPassword, arg.ID, arg.PasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserPasswordIfCurrent = `-- name: UpdateUserPasswordIfCurrent :execrows
UPDATE users
SET password_hash = $1, updated_at = now()
WHERE id = $2
  AND password_hash = $3
`

type UpdateUserPasswordIfCurrentParams struct {
	NewPasswordHash     string
	ID                  uuid.UUID
	CurrentPasswordHash string
}

func (q *Queries) UpdateUserPasswordIfCurrent(ctx context.Context, arg UpdateUserPasswordIfCurrentParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserPasswordIfCurrent, arg.NewPasswordHash, arg.ID, arg.CurrentPasswordHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserProfile = `-- name: UpdateUserProfile :one
UPDATE users
SET name           = COALESCE($1, name),
    birth_date     = CASE WHEN 'birth_date' = ANY($2::text[]) THEN NULL
                          ELSE COALESCE($3, birth_date) END,
    phone          = CASE WHEN 'phone' = ANY($2::text[]) THEN NULL
                          ELSE COALESCE($4, phone) END,
    cnh_category   = CASE WHEN 'cnh_category' = ANY($2::text[]) THEN NULL
                          ELSE COALESCE($5, cnh_category) END,
    cnh_expires_on = CASE WHEN 'cnh_expires_on' = ANY($2::text[]) THEN NULL
                          ELSE COALESCE($6, cnh_expires_on) END,
    updated_at     = now()
WHERE id = $7
RETURNING id, email, password_hash, name, created_at, updated_at, birth_date, phone, cnh_category, cnh_expires_on, photo_key
`

type UpdateUserProfileParams struct {
	Name         *string
	Clear        []string
	BirthDate    *time.Time
	Phone        *string
	CnhCategory  *string
	CnhExpiresOn *time.Time
	ID           uuid.UUID
}

// PATCH semantics: a NULL argument leaves the column untouched, and a column named in
// `clear` is set back to NULL. name is NOT NULL and is never in `clear`.
func (q *Queries) UpdateUserProfile(ctx context.Context, arg UpdateUserProfileParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUserProfile,
		arg.Name,
		arg.Clear,
		arg.BirthDate,
		arg.Phone,
		arg.CnhCategory,
		arg.CnhExpiresOn,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.PasswordHash,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BirthDate,
		&i.Phone,
		&i.CnhCategory,
		&i.CnhExpiresOn,
		&i.PhotoKey,
	)
	return i, err
}
