// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: devices.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const deleteDeviceByToken = `-- name: DeleteDeviceByToken :exec
DELETE FROM push_devices
WHERE token = $1
`

// A token FCM reported as gone (uninstalled app, cleared data, token rotated).
func (q *Queries) DeleteDeviceByToken(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, deleteDeviceByToken, token)
	return err
}

const deleteDeviceForUser = `-- name: DeleteDeviceForUser :execrows
DELETE FROM push_devices
WHERE token = $1 AND user_id = $2
`

type DeleteDeviceForUserParams struct {
	Token  string
	UserID uuid.UUID
}

// Forgets a phone. Only the caller's own row: a token is not a credential, and knowing one
// must not let anybody unsubscribe somebody else's phone.
func (q *Queries) DeleteDeviceForUser(ctx context.Context, arg DeleteDeviceForUserParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteDeviceForUser, arg.Token, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listDeviceTokensForUser = `-- name: ListDeviceTokensForUser :many
SELECT token
FROM push_devices
WHERE user_id = $1
ORDER BY created_at
`

func (q *Queries) ListDeviceTokensForUser(ctx context.Context, userID uuid.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, listDeviceTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var token string
		if err := rows.Scan(&token); err != nil {
			return nil, err
		}
		items = append(items, token)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUsersWithDevices = `-- name: ListUsersWithDevices :many
SELECT DISTINCT user_id
FROM push_devices
`

// Everybody a reminder could reach. Without a phone there is nobody to tell, so the job
// never looks at an account that has none.
func (q *Queries) ListUsersWithDevices(ctx context.Context) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listUsersWithDevices)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDevice = `-- name: UpsertDevice :exec
INSERT INTO push_devices (user_id, token, platform)
VALUES ($1, $2, $3)
ON CONFLICT (token) DO UPDATE
SET user_id      = EXCLUDED.user_id,
    platform     = EXCLUDED.platform,
    last_seen_at = now()
`

type UpsertDeviceParams struct {
	UserID   uuid.UUID
	Token    string
	Platform string
}

// Registers or reconfirms a phone.
//
// An existing token CHANGES OWNER instead of duplicating: FCM delivers to an installation,
// not to an account, and when another person signs in on the same phone the reminders
// about the previous owner's car must stop going there.
func (q *Queries) UpsertDevice(ctx context.Context, arg UpsertDeviceParams) error {
	_, err := q.db.Exec(ctx, upsertDevice, arg.UserID, arg.Token, arg.Platform)
	return err
}
