// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: log.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const recordReminder = `-- name: RecordReminder :execrows
INSERT INTO notification_log (user_id, vehicle_id, kind, subject_id, marker, sent_on)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (user_id, kind, subject_id, marker) DO NOTHING
`

type RecordReminderParams struct {
	UserID    uuid.UUID
	VehicleID uuid.UUID
	Kind      string
	SubjectID uuid.UUID
	Marker    string
	SentOn    time.Time
}

// Records that a reminder is going out, reporting 0 rows when it already went out before.
//
// Written BEFORE the push is sent. If the process dies between the two, one reminder is
// lost — far better than the alternative: a job that repeats itself every ten minutes.
func (q *Queries) RecordReminder(ctx context.Context, arg RecordReminderParams) (int64, error) {
	result, err := q.db.Exec(ctx, recordReminder,
		arg.UserID,
		arg.VehicleID,
		arg.Kind,
		arg.SubjectID,
		arg.Marker,
		arg.SentOn,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const vehicleRemindedOn = `-- name: VehicleRemindedOn :one
SELECT EXISTS (
    SELECT 1
    FROM notification_log
    WHERE user_id = $1 AND vehicle_id = $2 AND sent_on = $3
)
`

type VehicleRemindedOnParams struct {
	UserID    uuid.UUID
	VehicleID uuid.UUID
	SentOn    time.Time
}

// Whether this person already got a reminder about this car today. One push per car per
// day: what becomes due after the morning's push waits for tomorrow's.
func (q *Queries) VehicleRemindedOn(ctx context.Context, arg VehicleRemindedOnParams) (bool, error) {
	row := q.db.QueryRow(ctx, vehicleRemindedOn, arg.UserID, arg.VehicleID, arg.SentOn)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
