// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: brands.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const getVehicleBrand = `-- name: GetVehicleBrand :one
SELECT id, provider, vehicle_type, external_id, name, synced_at, models_synced_at, created_at, updated_at
FROM vehicle_brands
WHERE id = $1
`

func (q *Queries) GetVehicleBrand(ctx context.Context, id uuid.UUID) (VehicleBrand, error) {
	row := q.db.QueryRow(ctx, getVehicleBrand, id)
	var i VehicleBrand
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.VehicleType,
		&i.ExternalID,
		&i.Name,
		&i.SyncedAt,
		&i.ModelsSyncedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVehicleCatalogSync = `-- name: GetVehicleCatalogSync :one
SELECT synced_at
FROM vehicle_catalog_syncs
WHERE provider = $1
  AND vehicle_type = $2
`

type GetVehicleCatalogSyncParams struct {
	Provider    string
	VehicleType string
}

// When the brand list for this provider and vehicle type was last fully fetched.
// NULL means never, which is what sends the first request to the provider.
func (q *Queries) GetVehicleCatalogSync(ctx context.Context, arg GetVehicleCatalogSyncParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, getVehicleCatalogSync, arg.Provider, arg.VehicleType)
	var synced_at time.Time
	err := row.Scan(&synced_at)
	return synced_at, err
}

const listVehicleBrands = `-- name: ListVehicleBrands :many
SELECT id, provider, vehicle_type, external_id, name, synced_at, models_synced_at, created_at, updated_at
FROM vehicle_brands
WHERE provider = $1
  AND vehicle_type = $2
ORDER BY name
`

type ListVehicleBrandsParams struct {
	Provider    string
	VehicleType string
}

// The brand list as the app sees it.
func (q *Queries) ListVehicleBrands(ctx context.Context, arg ListVehicleBrandsParams) ([]VehicleBrand, error) {
	rows, err := q.db.Query(ctx, listVehicleBrands, arg.Provider, arg.VehicleType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VehicleBrand{}
	for rows.Next() {
		var i VehicleBrand
		if err := rows.Scan(
			&i.ID,
			&i.Provider,
			&i.VehicleType,
			&i.ExternalID,
			&i.Name,
			&i.SyncedAt,
			&i.ModelsSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVehicleBrandModelsSynced = `-- name: MarkVehicleBrandModelsSynced :exec
UPDATE vehicle_brands
SET models_synced_at = now(),
    updated_at       = now()
WHERE id = $1
`

func (q *Queries) MarkVehicleBrandModelsSynced(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markVehicleBrandModelsSynced, id)
	return err
}

const markVehicleCatalogSynced = `-- name: MarkVehicleCatalogSynced :exec
INSERT INTO vehicle_catalog_syncs (provider, vehicle_type, synced_at)
VALUES ($1, $2, now())
ON CONFLICT (provider, vehicle_type)
DO UPDATE SET synced_at = now()
`

type MarkVehicleCatalogSyncedParams struct {
	Provider    string
	VehicleType string
}

func (q *Queries) MarkVehicleCatalogSynced(ctx context.Context, arg MarkVehicleCatalogSyncedParams) error {
	_, err := q.db.Exec(ctx, markVehicleCatalogSynced, arg.Provider, arg.VehicleType)
	return err
}

const upsertVehicleBrands = `-- name: UpsertVehicleBrands :exec
INSERT INTO vehicle_brands (provider, vehicle_type, external_id, name)
SELECT $1, $2, e.external_id, n.name
FROM unnest($3::text[]) WITH ORDINALITY AS e (external_id, idx)
JOIN unnest($4::text[])        WITH ORDINALITY AS n (name, idx)
  USING (idx)
ON CONFLICT (provider, vehicle_type, external_id)
DO UPDATE SET name       = EXCLUDED.name,
              synced_at  = now(),
              updated_at = now()
`

type UpsertVehicleBrandsParams struct {
	Provider    string
	VehicleType string
	ExternalIds []string
	Names       []string
}

// Upsert the whole brand list in one statement.
//
// The arrays are unnested into rows rather than sent as N inserts: a brand list is around
// a hundred entries, and a hundred round trips inside one transaction is the difference
// between a fast first request and a slow one.
//
// ON CONFLICT DO UPDATE is what makes concurrency a non-event. Two users can trigger this
// sync at the same instant; the second one collides on
// (provider, vehicle_type, external_id) and refreshes the row instead of duplicating it.
// The UNIQUE constraint is the lock — there is no other one, and none is needed.
//
// models_synced_at is deliberately NOT touched here. Re-syncing the brand list must not
// forget that we already have Toyota's models.
func (q *Queries) UpsertVehicleBrands(ctx context.Context, arg UpsertVehicleBrandsParams) error {
	_, err := q.db.Exec(ctx, upsertVehicleBrands,
		arg.Provider,
		arg.VehicleType,
		arg.ExternalIds,
		arg.Names,
	)
	return err
}
