// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: models.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getVehicleModelWithBrand = `-- name: GetVehicleModelWithBrand :one
SELECT m.id, m.brand_id, m.external_id, m.name, m.synced_at, m.years_synced_at, m.created_at, m.updated_at, b.id, b.provider, b.vehicle_type, b.external_id, b.name, b.synced_at, b.models_synced_at, b.created_at, b.updated_at
FROM vehicle_models m
JOIN vehicle_brands b ON b.id = m.brand_id
WHERE m.id = $1
`

type GetVehicleModelWithBrandRow struct {
	VehicleModel VehicleModel
	VehicleBrand VehicleBrand
}

// The model plus the brand it belongs to, in one read.
//
// Every model-scoped request needs both: the brand carries the vehicle_type and the
// provider's brand id, and the provider's URL for "the years of this model" needs both
// ids. Fetching them separately would be two round trips for one fact.
func (q *Queries) GetVehicleModelWithBrand(ctx context.Context, id uuid.UUID) (GetVehicleModelWithBrandRow, error) {
	row := q.db.QueryRow(ctx, getVehicleModelWithBrand, id)
	var i GetVehicleModelWithBrandRow
	err := row.Scan(
		&i.VehicleModel.ID,
		&i.VehicleModel.BrandID,
		&i.VehicleModel.ExternalID,
		&i.VehicleModel.Name,
		&i.VehicleModel.SyncedAt,
		&i.VehicleModel.YearsSyncedAt,
		&i.VehicleModel.CreatedAt,
		&i.VehicleModel.UpdatedAt,
		&i.VehicleBrand.ID,
		&i.VehicleBrand.Provider,
		&i.VehicleBrand.VehicleType,
		&i.VehicleBrand.ExternalID,
		&i.VehicleBrand.Name,
		&i.VehicleBrand.SyncedAt,
		&i.VehicleBrand.ModelsSyncedAt,
		&i.VehicleBrand.CreatedAt,
		&i.VehicleBrand.UpdatedAt,
	)
	return i, err
}

const listVehicleModels = `-- name: ListVehicleModels :many
SELECT id, brand_id, external_id, name, synced_at, years_synced_at, created_at, updated_at
FROM vehicle_models
WHERE brand_id = $1
ORDER BY name
`

func (q *Queries) ListVehicleModels(ctx context.Context, brandID uuid.UUID) ([]VehicleModel, error) {
	rows, err := q.db.Query(ctx, listVehicleModels, brandID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VehicleModel{}
	for rows.Next() {
		var i VehicleModel
		if err := rows.Scan(
			&i.ID,
			&i.BrandID,
			&i.ExternalID,
			&i.Name,
			&i.SyncedAt,
			&i.YearsSyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markVehicleModelYearsSynced = `-- name: MarkVehicleModelYearsSynced :exec
UPDATE vehicle_models
SET years_synced_at = now(),
    updated_at      = now()
WHERE id = $1
`

func (q *Queries) MarkVehicleModelYearsSynced(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markVehicleModelYearsSynced, id)
	return err
}

const upsertVehicleModels = `-- name: UpsertVehicleModels :exec
INSERT INTO vehicle_models (brand_id, external_id, name)
SELECT $1, e.external_id, n.name
FROM unnest($2::text[]) WITH ORDINALITY AS e (external_id, idx)
JOIN unnest($3::text[])        WITH ORDINALITY AS n (name, idx)
  USING (idx)
ON CONFLICT (brand_id, external_id)
DO UPDATE SET name       = EXCLUDED.name,
              synced_at  = now(),
              updated_at = now()
`

type UpsertVehicleModelsParams struct {
	BrandID     uuid.UUID
	ExternalIds []string
	Names       []string
}

func (q *Queries) UpsertVehicleModels(ctx context.Context, arg UpsertVehicleModelsParams) error {
	_, err := q.db.Exec(ctx, upsertVehicleModels, arg.BrandID, arg.ExternalIds, arg.Names)
	return err
}
