// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: years.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const getVehicleCatalogSelection = `-- name: GetVehicleCatalogSelection :one
SELECT y.id AS model_year_id, m.id AS model_id, b.id AS brand_id
FROM vehicle_model_years y
JOIN vehicle_models m ON m.id = y.model_id
JOIN vehicle_brands b ON b.id = m.brand_id
WHERE y.id = $1
`

type GetVehicleCatalogSelectionRow struct {
	ModelYearID uuid.UUID
	ModelID     uuid.UUID
	BrandID     uuid.UUID
}

// The vehicle module resolves a catalogue selection through this, to confirm the id a
// client sent is real and to link the vehicle to all three levels at once.
//
// It is a read of reference data every account may see, so there is no ownership filter
// here and there is nothing to leak: a brand and a model are public facts.
func (q *Queries) GetVehicleCatalogSelection(ctx context.Context, id uuid.UUID) (GetVehicleCatalogSelectionRow, error) {
	row := q.db.QueryRow(ctx, getVehicleCatalogSelection, id)
	var i GetVehicleCatalogSelectionRow
	err := row.Scan(&i.ModelYearID, &i.ModelID, &i.BrandID)
	return i, err
}

const getVehicleModelYearWithParents = `-- name: GetVehicleModelYearWithParents :one
SELECT y.id, y.model_id, y.external_id, y.name, y.year, y.fuel_label, y.fuel_type, y.fipe_code, y.synced_at, y.created_at, y.updated_at, m.id, m.brand_id, m.external_id, m.name, m.synced_at, m.years_synced_at, m.created_at, m.updated_at, b.id, b.provider, b.vehicle_type, b.external_id, b.name, b.synced_at, b.models_synced_at, b.created_at, b.updated_at
FROM vehicle_model_years y
JOIN vehicle_models m ON m.id = y.model_id
JOIN vehicle_brands b ON b.id = m.brand_id
WHERE y.id = $1
`

type GetVehicleModelYearWithParentsRow struct {
	VehicleModelYear VehicleModelYear
	VehicleModel     VehicleModel
	VehicleBrand     VehicleBrand
}

// The full chain for the detail endpoint: the year, its model and its brand.
//
// One read rather than three. The brand is what carries vehicle_type and the provider,
// and the provider's detail URL needs all three external ids at once.
func (q *Queries) GetVehicleModelYearWithParents(ctx context.Context, id uuid.UUID) (GetVehicleModelYearWithParentsRow, error) {
	row := q.db.QueryRow(ctx, getVehicleModelYearWithParents, id)
	var i GetVehicleModelYearWithParentsRow
	err := row.Scan(
		&i.VehicleModelYear.ID,
		&i.VehicleModelYear.ModelID,
		&i.VehicleModelYear.ExternalID,
		&i.VehicleModelYear.Name,
		&i.VehicleModelYear.Year,
		&i.VehicleModelYear.FuelLabel,
		&i.VehicleModelYear.FuelType,
		&i.VehicleModelYear.FipeCode,
		&i.VehicleModelYear.SyncedAt,
		&i.VehicleModelYear.CreatedAt,
		&i.VehicleModelYear.UpdatedAt,
		&i.VehicleModel.ID,
		&i.VehicleModel.BrandID,
		&i.VehicleModel.ExternalID,
		&i.VehicleModel.Name,
		&i.VehicleModel.SyncedAt,
		&i.VehicleModel.YearsSyncedAt,
		&i.VehicleModel.CreatedAt,
		&i.VehicleModel.UpdatedAt,
		&i.VehicleBrand.ID,
		&i.VehicleBrand.Provider,
		&i.VehicleBrand.VehicleType,
		&i.VehicleBrand.ExternalID,
		&i.VehicleBrand.Name,
		&i.VehicleBrand.SyncedAt,
		&i.VehicleBrand.ModelsSyncedAt,
		&i.VehicleBrand.CreatedAt,
		&i.VehicleBrand.UpdatedAt,
	)
	return i, err
}

const listVehicleModelYears = `-- name: ListVehicleModelYears :many
SELECT id, model_id, external_id, name, year, fuel_label, fuel_type, fipe_code, synced_at, created_at, updated_at
FROM vehicle_model_years
WHERE model_id = $1
ORDER BY year DESC NULLS FIRST, name DESC
`

// Newest first: a picker showing 1998 above 2024 is a picker nobody scrolls to the
// bottom of. NULLS FIRST puts the provider's "zero km" entry at the top, where a brand
// new car belongs.
func (q *Queries) ListVehicleModelYears(ctx context.Context, modelID uuid.UUID) ([]VehicleModelYear, error) {
	rows, err := q.db.Query(ctx, listVehicleModelYears, modelID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VehicleModelYear{}
	for rows.Next() {
		var i VehicleModelYear
		if err := rows.Scan(
			&i.ID,
			&i.ModelID,
			&i.ExternalID,
			&i.Name,
			&i.Year,
			&i.FuelLabel,
			&i.FuelType,
			&i.FipeCode,
			&i.SyncedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setVehicleModelYearFipeCode = `-- name: SetVehicleModelYearFipeCode :exec
UPDATE vehicle_model_years
SET fipe_code  = $1,
    synced_at  = now(),
    updated_at = now()
WHERE id = $2
`

type SetVehicleModelYearFipeCodeParams struct {
	FipeCode *string
	ID       uuid.UUID
}

// Records the FIPE code the detail request revealed.
func (q *Queries) SetVehicleModelYearFipeCode(ctx context.Context, arg SetVehicleModelYearFipeCodeParams) error {
	_, err := q.db.Exec(ctx, setVehicleModelYearFipeCode, arg.FipeCode, arg.ID)
	return err
}

const upsertVehicleModelYears = `-- name: UpsertVehicleModelYears :exec
INSERT INTO vehicle_model_years (model_id, external_id, name, year, fuel_label, fuel_type)
SELECT $1,
       e.external_id,
       n.name,
       NULLIF(y.year, '')::integer,
       NULLIF(fl.fuel_label, ''),
       NULLIF(ft.fuel_type, '')
FROM unnest($2::text[]) WITH ORDINALITY AS e  (external_id, idx)
JOIN unnest($3::text[])        WITH ORDINALITY AS n  (name, idx)       USING (idx)
JOIN unnest($4::text[])        WITH ORDINALITY AS y  (year, idx)       USING (idx)
JOIN unnest($5::text[])  WITH ORDINALITY AS fl (fuel_label, idx) USING (idx)
JOIN unnest($6::text[])   WITH ORDINALITY AS ft (fuel_type, idx)  USING (idx)
ON CONFLICT (model_id, external_id)
DO UPDATE SET name       = EXCLUDED.name,
              year       = EXCLUDED.year,
              fuel_label = EXCLUDED.fuel_label,
              fuel_type  = EXCLUDED.fuel_type,
              synced_at  = now(),
              updated_at = now()
`

type UpsertVehicleModelYearsParams struct {
	ModelID     uuid.UUID
	ExternalIds []string
	Names       []string
	Years       []string
	FuelLabels  []string
	FuelTypes   []string
}

// Everything arrives as text[], including the year.
//
// Not because a year is text, but because unnest of an integer[] cannot carry a NULL
// element through sqlc's generated []int32 — and a NULL year is a real case: the
// provider's "zero km" pseudo-year has no year at all. NULLIF turns the empty string back
// into NULL at the boundary, and the column stays a proper integer. The same trick gives
// the two optional fuel columns their NULLs.
//
// The parallel arrays are zipped with WITH ORDINALITY rather than passed to the
// multi-argument unnest, which reads better but which sqlc cannot type: its catalogue
// only knows unnest(anyarray), so `unnest(a, b)` fails generation with "function
// unnest(unknown, unknown) does not exist". Joining on the ordinality is the same plan to
// Postgres and the same one round trip.
//
// fipe_code is untouched here on purpose. It only arrives with the detail request, and a
// re-sync of the year list must not wipe a code we already paid a request for.
func (q *Queries) UpsertVehicleModelYears(ctx context.Context, arg UpsertVehicleModelYearsParams) error {
	_, err := q.db.Exec(ctx, upsertVehicleModelYears,
		arg.ModelID,
		arg.ExternalIds,
		arg.Names,
		arg.Years,
		arg.FuelLabels,
		arg.FuelTypes,
	)
	return err
}
