// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: abastecimentos.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createAbastecimento = `-- name: CreateAbastecimento :one
INSERT INTO abastecimentos (
    id, vehicle_id, occurred_on, mileage_km, volume_ml, total_cost_cents,
    fuel, full_tank, station_name, notes, recorded_by_user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (id) DO NOTHING
RETURNING id, vehicle_id, occurred_on, mileage_km, volume_ml, total_cost_cents, fuel, full_tank, station_name, notes, recorded_by_user_id, created_at, updated_at
`

type CreateAbastecimentoParams struct {
	ID               uuid.UUID
	VehicleID        uuid.UUID
	OccurredOn       time.Time
	MileageKm        int32
	VolumeMl         int32
	TotalCostCents   int64
	Fuel             string
	FullTank         bool
	StationName      *string
	Notes            *string
	RecordedByUserID *uuid.UUID
}

func (q *Queries) CreateAbastecimento(ctx context.Context, arg CreateAbastecimentoParams) (Abastecimento, error) {
	row := q.db.QueryRow(ctx, createAbastecimento,
		arg.ID,
		arg.VehicleID,
		arg.OccurredOn,
		arg.MileageKm,
		arg.VolumeMl,
		arg.TotalCostCents,
		arg.Fuel,
		arg.FullTank,
		arg.StationName,
		arg.Notes,
		arg.RecordedByUserID,
	)
	var i Abastecimento
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.OccurredOn,
		&i.MileageKm,
		&i.VolumeMl,
		&i.TotalCostCents,
		&i.Fuel,
		&i.FullTank,
		&i.StationName,
		&i.Notes,
		&i.RecordedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createAbastecimentoOdometerReading = `-- name: CreateAbastecimentoOdometerReading :exec
INSERT INTO odometer_readings (
    vehicle_id, mileage_km, occurred_on, source, recorded_by_user_id, source_abastecimento_id
)
VALUES ($1, $2, $3, 'abastecimento', $4, $5)
`

type CreateAbastecimentoOdometerReadingParams struct {
	VehicleID             uuid.UUID
	MileageKm             int32
	OccurredOn            time.Time
	RecordedByUserID      *uuid.UUID
	SourceAbastecimentoID *uuid.UUID
}

// Writes to odometer_readings from this module.
//
// odometer_readings is co-owned by design: the vehicle module owns manual readings and
// every read of the log, but any module may append a reading tagged with its own source,
// inside its own transaction. The cache stays correct either way, because the trigger
// does not care who wrote the row.
func (q *Queries) CreateAbastecimentoOdometerReading(ctx context.Context, arg CreateAbastecimentoOdometerReadingParams) error {
	_, err := q.db.Exec(ctx, createAbastecimentoOdometerReading,
		arg.VehicleID,
		arg.MileageKm,
		arg.OccurredOn,
		arg.RecordedByUserID,
		arg.SourceAbastecimentoID,
	)
	return err
}

const deleteAbastecimento = `-- name: DeleteAbastecimento :execrows
DELETE FROM abastecimentos WHERE id = $1
`

func (q *Queries) DeleteAbastecimento(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAbastecimento, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getAbastecimentoByID = `-- name: GetAbastecimentoByID :one
SELECT id, vehicle_id, occurred_on, mileage_km, volume_ml, total_cost_cents, fuel, full_tank, station_name, notes, recorded_by_user_id, created_at, updated_at FROM abastecimentos WHERE id = $1
`

// Used only on the idempotency path, immediately after an id conflict, and always with
// the caller's vehicle already authorised and the returned vehicle_id compared. It is not
// an authorisation bypass; every request-facing read uses the query below.
func (q *Queries) GetAbastecimentoByID(ctx context.Context, id uuid.UUID) (Abastecimento, error) {
	row := q.db.QueryRow(ctx, getAbastecimentoByID, id)
	var i Abastecimento
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.OccurredOn,
		&i.MileageKm,
		&i.VolumeMl,
		&i.TotalCostCents,
		&i.Fuel,
		&i.FullTank,
		&i.StationName,
		&i.Notes,
		&i.RecordedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAbastecimentoForUser = `-- name: GetAbastecimentoForUser :one
SELECT a.id, a.vehicle_id, a.occurred_on, a.mileage_km, a.volume_ml, a.total_cost_cents, a.fuel, a.full_tank, a.station_name, a.notes, a.recorded_by_user_id, a.created_at, a.updated_at
FROM abastecimentos a
JOIN vehicle_ownerships o ON o.vehicle_id = a.vehicle_id
WHERE a.id = $1
  AND o.user_id = $2
  AND o.ended_on IS NULL
`

type GetAbastecimentoForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Fills are read through the vehicle, never by id alone — the same rule as vehicles
// (SPEC.md RN-07). The join is the authorisation.
func (q *Queries) GetAbastecimentoForUser(ctx context.Context, arg GetAbastecimentoForUserParams) (Abastecimento, error) {
	row := q.db.QueryRow(ctx, getAbastecimentoForUser, arg.ID, arg.UserID)
	var i Abastecimento
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.OccurredOn,
		&i.MileageKm,
		&i.VolumeMl,
		&i.TotalCostCents,
		&i.Fuel,
		&i.FullTank,
		&i.StationName,
		&i.Notes,
		&i.RecordedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listAbastecimentosForVehicle = `-- name: ListAbastecimentosForVehicle :many
SELECT id, vehicle_id, occurred_on, mileage_km, volume_ml, total_cost_cents, fuel, full_tank, station_name, notes, recorded_by_user_id, created_at, updated_at
FROM abastecimentos
WHERE vehicle_id = $1
  AND (
        $2::date IS NULL
        OR (occurred_on, created_at, id) <
           ($2::date,
            $3::timestamptz,
            $4::uuid)
      )
ORDER BY occurred_on DESC, created_at DESC, id DESC
LIMIT $5
`

type ListAbastecimentosForVehicleParams struct {
	VehicleID        uuid.UUID
	CursorOccurredOn *time.Time
	CursorCreatedAt  *time.Time
	CursorID         *uuid.UUID
	PageSize         int32
}

// Keyset pagination, newest first.
func (q *Queries) ListAbastecimentosForVehicle(ctx context.Context, arg ListAbastecimentosForVehicleParams) ([]Abastecimento, error) {
	rows, err := q.db.Query(ctx, listAbastecimentosForVehicle,
		arg.VehicleID,
		arg.CursorOccurredOn,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Abastecimento{}
	for rows.Next() {
		var i Abastecimento
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.OccurredOn,
			&i.MileageKm,
			&i.VolumeMl,
			&i.TotalCostCents,
			&i.Fuel,
			&i.FullTank,
			&i.StationName,
			&i.Notes,
			&i.RecordedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllAbastecimentosForVehicle = `-- name: ListAllAbastecimentosForVehicle :many
SELECT id, vehicle_id, occurred_on, mileage_km, volume_ml, total_cost_cents, fuel, full_tank, station_name, notes, recorded_by_user_id, created_at, updated_at
FROM abastecimentos
WHERE vehicle_id = $1
ORDER BY occurred_on ASC, created_at ASC, id ASC
`

// The full history, oldest first, for the consumption walk. Consumption is never stored,
// so every read recomputes from this sequence.
func (q *Queries) ListAllAbastecimentosForVehicle(ctx context.Context, vehicleID uuid.UUID) ([]Abastecimento, error) {
	rows, err := q.db.Query(ctx, listAllAbastecimentosForVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Abastecimento{}
	for rows.Next() {
		var i Abastecimento
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.OccurredOn,
			&i.MileageKm,
			&i.VolumeMl,
			&i.TotalCostCents,
			&i.Fuel,
			&i.FullTank,
			&i.StationName,
			&i.Notes,
			&i.RecordedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAbastecimento = `-- name: UpdateAbastecimento :one
UPDATE abastecimentos
SET occurred_on      = COALESCE($1, occurred_on),
    mileage_km       = COALESCE($2, mileage_km),
    volume_ml        = COALESCE($3, volume_ml),
    total_cost_cents = COALESCE($4, total_cost_cents),
    fuel             = COALESCE($5, fuel),
    full_tank        = COALESCE($6, full_tank),
    station_name     = COALESCE($7, station_name),
    notes            = COALESCE($8, notes),
    updated_at       = now()
WHERE id = $9
RETURNING id, vehicle_id, occurred_on, mileage_km, volume_ml, total_cost_cents, fuel, full_tank, station_name, notes, recorded_by_user_id, created_at, updated_at
`

type UpdateAbastecimentoParams struct {
	OccurredOn     *time.Time
	MileageKm      *int32
	VolumeMl       *int32
	TotalCostCents *int64
	Fuel           *string
	FullTank       *bool
	StationName    *string
	Notes          *string
	ID             uuid.UUID
}

func (q *Queries) UpdateAbastecimento(ctx context.Context, arg UpdateAbastecimentoParams) (Abastecimento, error) {
	row := q.db.QueryRow(ctx, updateAbastecimento,
		arg.OccurredOn,
		arg.MileageKm,
		arg.VolumeMl,
		arg.TotalCostCents,
		arg.Fuel,
		arg.FullTank,
		arg.StationName,
		arg.Notes,
		arg.ID,
	)
	var i Abastecimento
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.OccurredOn,
		&i.MileageKm,
		&i.VolumeMl,
		&i.TotalCostCents,
		&i.Fuel,
		&i.FullTank,
		&i.StationName,
		&i.Notes,
		&i.RecordedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateAbastecimentoOdometerReading = `-- name: UpdateAbastecimentoOdometerReading :exec
UPDATE odometer_readings
SET mileage_km = $2, occurred_on = $3
WHERE source_abastecimento_id = $1
`

type UpdateAbastecimentoOdometerReadingParams struct {
	SourceAbastecimentoID *uuid.UUID
	MileageKm             int32
	OccurredOn            time.Time
}

func (q *Queries) UpdateAbastecimentoOdometerReading(ctx context.Context, arg UpdateAbastecimentoOdometerReadingParams) error {
	_, err := q.db.Exec(ctx, updateAbastecimentoOdometerReading, arg.SourceAbastecimentoID, arg.MileageKm, arg.OccurredOn)
	return err
}
