// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createCustomMaintenanceItem = `-- name: CreateCustomMaintenanceItem :one
INSERT INTO maintenance_items (
    id, slug, name, kind, vehicle_type, owner_user_id,
    default_interval_km, default_interval_months, default_interval_days,
    suggest_by_default
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, false)
ON CONFLICT (owner_user_id, slug) WHERE owner_user_id IS NOT NULL DO NOTHING
RETURNING id, slug, name, kind, vehicle_type, owner_user_id, default_interval_km, default_interval_months, default_interval_days, suggest_by_default, is_active, created_at
`

type CreateCustomMaintenanceItemParams struct {
	ID                    uuid.UUID
	Slug                  string
	Name                  string
	Kind                  string
	VehicleType           string
	OwnerUserID           *uuid.UUID
	DefaultIntervalKm     *int32
	DefaultIntervalMonths *int32
	DefaultIntervalDays   *int32
}

func (q *Queries) CreateCustomMaintenanceItem(ctx context.Context, arg CreateCustomMaintenanceItemParams) (MaintenanceItem, error) {
	row := q.db.QueryRow(ctx, createCustomMaintenanceItem,
		arg.ID,
		arg.Slug,
		arg.Name,
		arg.Kind,
		arg.VehicleType,
		arg.OwnerUserID,
		arg.DefaultIntervalKm,
		arg.DefaultIntervalMonths,
		arg.DefaultIntervalDays,
	)
	var i MaintenanceItem
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.VehicleType,
		&i.OwnerUserID,
		&i.DefaultIntervalKm,
		&i.DefaultIntervalMonths,
		&i.DefaultIntervalDays,
		&i.SuggestByDefault,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const getMaintenanceItem = `-- name: GetMaintenanceItem :one
SELECT id, slug, name, kind, vehicle_type, owner_user_id, default_interval_km, default_interval_months, default_interval_days, suggest_by_default, is_active, created_at
FROM maintenance_items
WHERE id = $1
  AND is_active
  AND (owner_user_id IS NULL OR owner_user_id = $2)
`

type GetMaintenanceItemParams struct {
	ID     uuid.UUID
	UserID *uuid.UUID
}

// Scoped the same way as the list: a user must not be able to reference somebody else's
// custom item by id.
func (q *Queries) GetMaintenanceItem(ctx context.Context, arg GetMaintenanceItemParams) (MaintenanceItem, error) {
	row := q.db.QueryRow(ctx, getMaintenanceItem, arg.ID, arg.UserID)
	var i MaintenanceItem
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Name,
		&i.Kind,
		&i.VehicleType,
		&i.OwnerUserID,
		&i.DefaultIntervalKm,
		&i.DefaultIntervalMonths,
		&i.DefaultIntervalDays,
		&i.SuggestByDefault,
		&i.IsActive,
		&i.CreatedAt,
	)
	return i, err
}

const listMaintenanceItems = `-- name: ListMaintenanceItems :many
SELECT id, slug, name, kind, vehicle_type, owner_user_id, default_interval_km, default_interval_months, default_interval_days, suggest_by_default, is_active, created_at
FROM maintenance_items
WHERE is_active
  AND (owner_user_id IS NULL OR owner_user_id = $1)
  AND (vehicle_type = 'all' OR vehicle_type = $2)
  AND ($3::text IS NULL OR kind = $3)
ORDER BY kind, name
`

type ListMaintenanceItemsParams struct {
	UserID      *uuid.UUID
	VehicleType string
	Kind        *string
}

// The catalogue a user can see: every global entry, plus their own custom items.
func (q *Queries) ListMaintenanceItems(ctx context.Context, arg ListMaintenanceItemsParams) ([]MaintenanceItem, error) {
	rows, err := q.db.Query(ctx, listMaintenanceItems, arg.UserID, arg.VehicleType, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceItem{}
	for rows.Next() {
		var i MaintenanceItem
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.VehicleType,
			&i.OwnerUserID,
			&i.DefaultIntervalKm,
			&i.DefaultIntervalMonths,
			&i.DefaultIntervalDays,
			&i.SuggestByDefault,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuggestedMaintenanceItems = `-- name: ListSuggestedMaintenanceItems :many
SELECT id, slug, name, kind, vehicle_type, owner_user_id, default_interval_km, default_interval_months, default_interval_days, suggest_by_default, is_active, created_at
FROM maintenance_items
WHERE owner_user_id IS NULL
  AND is_active
  AND suggest_by_default
  AND (vehicle_type = 'all' OR vehicle_type = $1)
ORDER BY kind, name
`

// The entries a new vehicle gets a plan for (SPEC.md RN-09).
func (q *Queries) ListSuggestedMaintenanceItems(ctx context.Context, vehicleType string) ([]MaintenanceItem, error) {
	rows, err := q.db.Query(ctx, listSuggestedMaintenanceItems, vehicleType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceItem{}
	for rows.Next() {
		var i MaintenanceItem
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Name,
			&i.Kind,
			&i.VehicleType,
			&i.OwnerUserID,
			&i.DefaultIntervalKm,
			&i.DefaultIntervalMonths,
			&i.DefaultIntervalDays,
			&i.SuggestByDefault,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
