// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMaintenancePlan = `-- name: CreateMaintenancePlan :one
INSERT INTO maintenance_plans (
    id, vehicle_id, maintenance_item_id,
    interval_km, interval_months, interval_days,
    alert_km, alert_days, origin
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (vehicle_id, maintenance_item_id) DO NOTHING
RETURNING id, vehicle_id, maintenance_item_id, interval_km, interval_months, interval_days, alert_km, alert_days, origin, is_active, created_at, updated_at
`

type CreateMaintenancePlanParams struct {
	ID                uuid.UUID
	VehicleID         uuid.UUID
	MaintenanceItemID uuid.UUID
	IntervalKm        *int32
	IntervalMonths    *int32
	IntervalDays      *int32
	AlertKm           int32
	AlertDays         int32
	Origin            string
}

// ON CONFLICT DO NOTHING makes materialising the suggested plans safe to run twice, and
// makes a client retry idempotent.
func (q *Queries) CreateMaintenancePlan(ctx context.Context, arg CreateMaintenancePlanParams) (MaintenancePlan, error) {
	row := q.db.QueryRow(ctx, createMaintenancePlan,
		arg.ID,
		arg.VehicleID,
		arg.MaintenanceItemID,
		arg.IntervalKm,
		arg.IntervalMonths,
		arg.IntervalDays,
		arg.AlertKm,
		arg.AlertDays,
		arg.Origin,
	)
	var i MaintenancePlan
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.MaintenanceItemID,
		&i.IntervalKm,
		&i.IntervalMonths,
		&i.IntervalDays,
		&i.AlertKm,
		&i.AlertDays,
		&i.Origin,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deactivateMaintenancePlan = `-- name: DeactivateMaintenancePlan :execrows
UPDATE maintenance_plans
SET is_active = false, updated_at = now()
WHERE id = $1 AND is_active
`

// Soft-disable rather than delete: the plan may already have history attached, and the
// owner may want it back.
func (q *Queries) DeactivateMaintenancePlan(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateMaintenancePlan, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMaintenancePlan = `-- name: GetMaintenancePlan :one
SELECT p.id, p.vehicle_id, p.maintenance_item_id, p.interval_km, p.interval_months, p.interval_days, p.alert_km, p.alert_days, p.origin, p.is_active, p.created_at, p.updated_at, i.slug AS item_slug, i.name AS item_name, i.kind AS item_kind
FROM maintenance_plans p
JOIN maintenance_items i ON i.id = p.maintenance_item_id
WHERE p.id = $1
`

type GetMaintenancePlanRow struct {
	ID                uuid.UUID
	VehicleID         uuid.UUID
	MaintenanceItemID uuid.UUID
	IntervalKm        *int32
	IntervalMonths    *int32
	IntervalDays      *int32
	AlertKm           int32
	AlertDays         int32
	Origin            string
	IsActive          bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ItemSlug          string
	ItemName          string
	ItemKind          string
}

func (q *Queries) GetMaintenancePlan(ctx context.Context, id uuid.UUID) (GetMaintenancePlanRow, error) {
	row := q.db.QueryRow(ctx, getMaintenancePlan, id)
	var i GetMaintenancePlanRow
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.MaintenanceItemID,
		&i.IntervalKm,
		&i.IntervalMonths,
		&i.IntervalDays,
		&i.AlertKm,
		&i.AlertDays,
		&i.Origin,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ItemSlug,
		&i.ItemName,
		&i.ItemKind,
	)
	return i, err
}

const listMaintenancePlansForVehicle = `-- name: ListMaintenancePlansForVehicle :many
SELECT p.id, p.vehicle_id, p.maintenance_item_id, p.interval_km, p.interval_months, p.interval_days, p.alert_km, p.alert_days, p.origin, p.is_active, p.created_at, p.updated_at, i.slug AS item_slug, i.name AS item_name, i.kind AS item_kind
FROM maintenance_plans p
JOIN maintenance_items i ON i.id = p.maintenance_item_id
WHERE p.vehicle_id = $1
  AND p.is_active
ORDER BY i.kind, i.name
`

type ListMaintenancePlansForVehicleRow struct {
	ID                uuid.UUID
	VehicleID         uuid.UUID
	MaintenanceItemID uuid.UUID
	IntervalKm        *int32
	IntervalMonths    *int32
	IntervalDays      *int32
	AlertKm           int32
	AlertDays         int32
	Origin            string
	IsActive          bool
	CreatedAt         time.Time
	UpdatedAt         time.Time
	ItemSlug          string
	ItemName          string
	ItemKind          string
}

// The item columns are joined in because every consumer needs them: the due engine wants
// the name for ordering, and the app wants it for display.
func (q *Queries) ListMaintenancePlansForVehicle(ctx context.Context, vehicleID uuid.UUID) ([]ListMaintenancePlansForVehicleRow, error) {
	rows, err := q.db.Query(ctx, listMaintenancePlansForVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaintenancePlansForVehicleRow{}
	for rows.Next() {
		var i ListMaintenancePlansForVehicleRow
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.MaintenanceItemID,
			&i.IntervalKm,
			&i.IntervalMonths,
			&i.IntervalDays,
			&i.AlertKm,
			&i.AlertDays,
			&i.Origin,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ItemSlug,
			&i.ItemName,
			&i.ItemKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMaintenancePlan = `-- name: UpdateMaintenancePlan :one
UPDATE maintenance_plans
SET interval_km     = CASE WHEN $1::boolean THEN NULL
                           ELSE COALESCE($2, interval_km) END,
    interval_months = CASE WHEN $1::boolean THEN NULL
                           ELSE COALESCE($3, interval_months) END,
    interval_days   = CASE WHEN $1::boolean THEN NULL
                           ELSE COALESCE($4, interval_days) END,
    alert_km        = COALESCE($5, alert_km),
    alert_days      = COALESCE($6, alert_days),
    -- Any edit makes the plan the owner's, so a future refresh of the suggested defaults
    -- will not overwrite it.
    origin          = 'user',
    updated_at      = now()
WHERE id = $7
RETURNING id, vehicle_id, maintenance_item_id, interval_km, interval_months, interval_days, alert_km, alert_days, origin, is_active, created_at, updated_at
`

type UpdateMaintenancePlanParams struct {
	ClearIntervals bool
	IntervalKm     *int32
	IntervalMonths *int32
	IntervalDays   *int32
	AlertKm        *int32
	AlertDays      *int32
	ID             uuid.UUID
}

// PATCH semantics: a NULL argument leaves the column alone.
//
// Clearing an interval back to "no periodicity" therefore needs its own flag rather than
// a null, because null already means "unchanged" here.
func (q *Queries) UpdateMaintenancePlan(ctx context.Context, arg UpdateMaintenancePlanParams) (MaintenancePlan, error) {
	row := q.db.QueryRow(ctx, updateMaintenancePlan,
		arg.ClearIntervals,
		arg.IntervalKm,
		arg.IntervalMonths,
		arg.IntervalDays,
		arg.AlertKm,
		arg.AlertDays,
		arg.ID,
	)
	var i MaintenancePlan
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.MaintenanceItemID,
		&i.IntervalKm,
		&i.IntervalMonths,
		&i.IntervalDays,
		&i.AlertKm,
		&i.AlertDays,
		&i.Origin,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
