// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plans.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMaintenancePlan = `-- name: CreateMaintenancePlan :one
INSERT INTO maintenance_plans (
    id, vehicle_id, maintenance_item_id,
    interval_km, interval_months, interval_days,
    alert_km, alert_days, origin, strategy, notes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (vehicle_id, maintenance_item_id) DO NOTHING
RETURNING id, vehicle_id, maintenance_item_id, interval_km, interval_months, interval_days, alert_km, alert_days, origin, is_active, created_at, updated_at, strategy, history_status, notes
`

type CreateMaintenancePlanParams struct {
	ID                uuid.UUID
	VehicleID         uuid.UUID
	MaintenanceItemID uuid.UUID
	IntervalKm        *int32
	IntervalMonths    *int32
	IntervalDays      *int32
	AlertKm           int32
	AlertDays         int32
	Origin            string
	Strategy          string
	Notes             *string
}

// ON CONFLICT DO NOTHING makes materialising the suggested plans safe to run twice, and
// makes a client retry idempotent.
func (q *Queries) CreateMaintenancePlan(ctx context.Context, arg CreateMaintenancePlanParams) (MaintenancePlan, error) {
	row := q.db.QueryRow(ctx, createMaintenancePlan,
		arg.ID,
		arg.VehicleID,
		arg.MaintenanceItemID,
		arg.IntervalKm,
		arg.IntervalMonths,
		arg.IntervalDays,
		arg.AlertKm,
		arg.AlertDays,
		arg.Origin,
		arg.Strategy,
		arg.Notes,
	)
	var i MaintenancePlan
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.MaintenanceItemID,
		&i.IntervalKm,
		&i.IntervalMonths,
		&i.IntervalDays,
		&i.AlertKm,
		&i.AlertDays,
		&i.Origin,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Strategy,
		&i.HistoryStatus,
		&i.Notes,
	)
	return i, err
}

const deactivateMaintenancePlan = `-- name: DeactivateMaintenancePlan :execrows
UPDATE maintenance_plans
SET is_active = false, updated_at = now()
WHERE id = $1 AND is_active
`

// Soft-disable rather than delete: the plan may already have history attached, and the
// owner may want it back.
func (q *Queries) DeactivateMaintenancePlan(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deactivateMaintenancePlan, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const demoteImpossiblePlans = `-- name: DemoteImpossiblePlans :execrows

UPDATE maintenance_plans p
SET strategy = 'not_applicable', updated_at = now()
FROM maintenance_items i
WHERE i.id = p.maintenance_item_id
  AND p.vehicle_id = $1
  AND p.origin <> 'user'
  AND p.strategy <> 'not_applicable'
  AND i.powertrain_requirement = ANY ($2::text[])
  AND NOT EXISTS (
        SELECT 1
        FROM maintenance_record_items ri
        JOIN maintenance_records r ON r.id = ri.maintenance_record_id
        WHERE ri.maintenance_item_id = p.maintenance_item_id
          AND r.vehicle_id = p.vehicle_id
          AND r.deleted_at IS NULL
  )
`

type DemoteImpossiblePlansParams struct {
	VehicleID    uuid.UUID
	Requirements []string
}

// Correcting the vehicle's own fuel type has to correct what it needs.
//
// Someone who registered a car by hand, left the fuel blank and later said "elétrico" must
// stop being reminded to change the oil; someone who picked the wrong entry and fixes it
// must get their engine plans back. Neither is a new suggestion — it is the same derivation
// re-run against a vehicle that now says something different about itself.
//
// WHICH requirements a powertrain satisfies is decided in Go (maintenance/powertrain.go) and
// arrives here as a list. This SQL applies a verdict; it does not form one. That is what
// keeps one definition of what an electric car is.
// Guarded three ways, and each guard is load-bearing:
//   - origin <> 'user'  a decision the owner made is theirs, even when it looks wrong.
//   - no history        if the service was actually recorded, the FUEL TYPE is what is
//     wrong, not the plan. Never contradict a recorded fact.
//   - intervals kept    so restoring the item does not lose the rule.
func (q *Queries) DemoteImpossiblePlans(ctx context.Context, arg DemoteImpossiblePlansParams) (int64, error) {
	result, err := q.db.Exec(ctx, demoteImpossiblePlans, arg.VehicleID, arg.Requirements)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getMaintenancePlan = `-- name: GetMaintenancePlan :one
SELECT p.id, p.vehicle_id, p.maintenance_item_id, p.interval_km, p.interval_months, p.interval_days, p.alert_km, p.alert_days, p.origin, p.is_active, p.created_at, p.updated_at, p.strategy, p.history_status, p.notes,
       i.slug             AS item_slug,
       i.name             AS item_name,
       i.kind             AS item_kind,
       i.history_question AS item_history_question,
       i.history_priority AS item_history_priority
FROM maintenance_plans p
JOIN maintenance_items i ON i.id = p.maintenance_item_id
WHERE p.id = $1
`

type GetMaintenancePlanRow struct {
	ID                  uuid.UUID
	VehicleID           uuid.UUID
	MaintenanceItemID   uuid.UUID
	IntervalKm          *int32
	IntervalMonths      *int32
	IntervalDays        *int32
	AlertKm             int32
	AlertDays           int32
	Origin              string
	IsActive            bool
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Strategy            string
	HistoryStatus       string
	Notes               *string
	ItemSlug            string
	ItemName            string
	ItemKind            string
	ItemHistoryQuestion *string
	ItemHistoryPriority int32
}

func (q *Queries) GetMaintenancePlan(ctx context.Context, id uuid.UUID) (GetMaintenancePlanRow, error) {
	row := q.db.QueryRow(ctx, getMaintenancePlan, id)
	var i GetMaintenancePlanRow
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.MaintenanceItemID,
		&i.IntervalKm,
		&i.IntervalMonths,
		&i.IntervalDays,
		&i.AlertKm,
		&i.AlertDays,
		&i.Origin,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Strategy,
		&i.HistoryStatus,
		&i.Notes,
		&i.ItemSlug,
		&i.ItemName,
		&i.ItemKind,
		&i.ItemHistoryQuestion,
		&i.ItemHistoryPriority,
	)
	return i, err
}

const listMaintenancePlansForVehicle = `-- name: ListMaintenancePlansForVehicle :many
SELECT p.id, p.vehicle_id, p.maintenance_item_id, p.interval_km, p.interval_months, p.interval_days, p.alert_km, p.alert_days, p.origin, p.is_active, p.created_at, p.updated_at, p.strategy, p.history_status, p.notes,
       i.slug             AS item_slug,
       i.name             AS item_name,
       i.kind             AS item_kind,
       i.history_question AS item_history_question,
       i.history_priority AS item_history_priority
FROM maintenance_plans p
JOIN maintenance_items i ON i.id = p.maintenance_item_id
WHERE p.vehicle_id = $1
  AND p.is_active
  AND ($2::boolean OR p.strategy <> 'not_applicable')
ORDER BY i.kind, i.name
`

type ListMaintenancePlansForVehicleParams struct {
	VehicleID            uuid.UUID
	IncludeNotApplicable bool
}

type ListMaintenancePlansForVehicleRow struct {
	ID                  uuid.UUID
	VehicleID           uuid.UUID
	MaintenanceItemID   uuid.UUID
	IntervalKm          *int32
	IntervalMonths      *int32
	IntervalDays        *int32
	AlertKm             int32
	AlertDays           int32
	Origin              string
	IsActive            bool
	CreatedAt           time.Time
	UpdatedAt           time.Time
	Strategy            string
	HistoryStatus       string
	Notes               *string
	ItemSlug            string
	ItemName            string
	ItemKind            string
	ItemHistoryQuestion *string
	ItemHistoryPriority int32
}

// The item columns are joined in because every consumer needs them: the due engine wants
// the name for ordering, the app wants it for display, and the history prompt wants the
// question and its rank — which used to be a hard-coded list of slugs inside the app.
//
// `include_not_applicable` defaults to false at every call site that renders a screen. An
// item the vehicle does not have is not hidden behind a disabled card; it is simply not
// there. The configuration screen is the one caller that passes true, because undoing has
// to be possible.
func (q *Queries) ListMaintenancePlansForVehicle(ctx context.Context, arg ListMaintenancePlansForVehicleParams) ([]ListMaintenancePlansForVehicleRow, error) {
	rows, err := q.db.Query(ctx, listMaintenancePlansForVehicle, arg.VehicleID, arg.IncludeNotApplicable)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaintenancePlansForVehicleRow{}
	for rows.Next() {
		var i ListMaintenancePlansForVehicleRow
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.MaintenanceItemID,
			&i.IntervalKm,
			&i.IntervalMonths,
			&i.IntervalDays,
			&i.AlertKm,
			&i.AlertDays,
			&i.Origin,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Strategy,
			&i.HistoryStatus,
			&i.Notes,
			&i.ItemSlug,
			&i.ItemName,
			&i.ItemKind,
			&i.ItemHistoryQuestion,
			&i.ItemHistoryPriority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restorePossiblePlans = `-- name: RestorePossiblePlans :execrows
UPDATE maintenance_plans p
SET strategy = i.default_strategy, updated_at = now()
FROM maintenance_items i
WHERE i.id = p.maintenance_item_id
  AND p.vehicle_id = $1
  AND p.origin <> 'user'
  AND p.strategy = 'not_applicable'
  AND i.powertrain_requirement = ANY ($2::text[])
`

type RestorePossiblePlansParams struct {
	VehicleID    uuid.UUID
	Requirements []string
}

// The other direction. `origin <> 'user'` here protects a "meu carro não tem isso" the owner
// set by hand, and the not-applicable half of a profile answer, from being switched back on
// by a fuel-type edit.
func (q *Queries) RestorePossiblePlans(ctx context.Context, arg RestorePossiblePlansParams) (int64, error) {
	result, err := q.db.Exec(ctx, restorePossiblePlans, arg.VehicleID, arg.Requirements)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMaintenancePlan = `-- name: UpdateMaintenancePlan :one
UPDATE maintenance_plans
SET interval_km     = CASE WHEN $1::boolean THEN NULL
                           ELSE COALESCE($2, interval_km) END,
    interval_months = CASE WHEN $1::boolean THEN NULL
                           ELSE COALESCE($3, interval_months) END,
    interval_days   = CASE WHEN $1::boolean THEN NULL
                           ELSE COALESCE($4, interval_days) END,
    alert_km        = COALESCE($5, alert_km),
    alert_days      = COALESCE($6, alert_days),
    strategy        = COALESCE($7, strategy),
    history_status  = COALESCE($8, history_status),
    notes           = CASE WHEN $9::boolean THEN NULL
                           ELSE COALESCE($10, notes) END,
    -- Any edit makes the plan the owner's, so a future refresh of the suggested defaults
    -- will not overwrite it.
    origin          = 'user',
    updated_at      = now()
WHERE id = $11
RETURNING id, vehicle_id, maintenance_item_id, interval_km, interval_months, interval_days, alert_km, alert_days, origin, is_active, created_at, updated_at, strategy, history_status, notes
`

type UpdateMaintenancePlanParams struct {
	ClearIntervals bool
	IntervalKm     *int32
	IntervalMonths *int32
	IntervalDays   *int32
	AlertKm        *int32
	AlertDays      *int32
	Strategy       *string
	HistoryStatus  *string
	ClearNotes     bool
	Notes          *string
	ID             uuid.UUID
}

// PATCH semantics: a NULL argument leaves the column alone.
//
// Clearing an interval back to "no periodicity" therefore needs its own flag rather than
// a null, because null already means "unchanged" here. Same for the note.
func (q *Queries) UpdateMaintenancePlan(ctx context.Context, arg UpdateMaintenancePlanParams) (MaintenancePlan, error) {
	row := q.db.QueryRow(ctx, updateMaintenancePlan,
		arg.ClearIntervals,
		arg.IntervalKm,
		arg.IntervalMonths,
		arg.IntervalDays,
		arg.AlertKm,
		arg.AlertDays,
		arg.Strategy,
		arg.HistoryStatus,
		arg.ClearNotes,
		arg.Notes,
		arg.ID,
	)
	var i MaintenancePlan
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.MaintenanceItemID,
		&i.IntervalKm,
		&i.IntervalMonths,
		&i.IntervalDays,
		&i.AlertKm,
		&i.AlertDays,
		&i.Origin,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Strategy,
		&i.HistoryStatus,
		&i.Notes,
	)
	return i, err
}

const upsertMaintenancePlanApplicability = `-- name: UpsertMaintenancePlanApplicability :one
INSERT INTO maintenance_plans (
    id, vehicle_id, maintenance_item_id,
    interval_km, interval_months, interval_days,
    alert_km, alert_days, origin, strategy, notes
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (vehicle_id, maintenance_item_id) DO UPDATE
SET strategy        = EXCLUDED.strategy,
    origin          = EXCLUDED.origin,
    is_active       = true,
    interval_km     = COALESCE(maintenance_plans.interval_km,     EXCLUDED.interval_km),
    interval_months = COALESCE(maintenance_plans.interval_months, EXCLUDED.interval_months),
    interval_days   = COALESCE(maintenance_plans.interval_days,   EXCLUDED.interval_days),
    notes           = COALESCE(EXCLUDED.notes, maintenance_plans.notes),
    updated_at      = now()
RETURNING id, vehicle_id, maintenance_item_id, interval_km, interval_months, interval_days, alert_km, alert_days, origin, is_active, created_at, updated_at, strategy, history_status, notes
`

type UpsertMaintenancePlanApplicabilityParams struct {
	ID                uuid.UUID
	VehicleID         uuid.UUID
	MaintenanceItemID uuid.UUID
	IntervalKm        *int32
	IntervalMonths    *int32
	IntervalDays      *int32
	AlertKm           int32
	AlertDays         int32
	Origin            string
	Strategy          string
	Notes             *string
}

// Used when the owner ANSWERS a question about how their car is built, which is a decision
// rather than a suggestion: it must land even if a plan for the item is already there.
//
// Existing intervals win over the catalogue's. Somebody who answered "corrente" after
// setting their own timing-belt interval keeps that number, in case they change the answer
// back.
func (q *Queries) UpsertMaintenancePlanApplicability(ctx context.Context, arg UpsertMaintenancePlanApplicabilityParams) (MaintenancePlan, error) {
	row := q.db.QueryRow(ctx, upsertMaintenancePlanApplicability,
		arg.ID,
		arg.VehicleID,
		arg.MaintenanceItemID,
		arg.IntervalKm,
		arg.IntervalMonths,
		arg.IntervalDays,
		arg.AlertKm,
		arg.AlertDays,
		arg.Origin,
		arg.Strategy,
		arg.Notes,
	)
	var i MaintenancePlan
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.MaintenanceItemID,
		&i.IntervalKm,
		&i.IntervalMonths,
		&i.IntervalDays,
		&i.AlertKm,
		&i.AlertDays,
		&i.Origin,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Strategy,
		&i.HistoryStatus,
		&i.Notes,
	)
	return i, err
}
