// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profile.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const listVehicleProfileAnswers = `-- name: ListVehicleProfileAnswers :many
SELECT vehicle_id, question, answer, source, answered_at FROM vehicle_profile_answers
WHERE vehicle_id = $1
ORDER BY question
`

func (q *Queries) ListVehicleProfileAnswers(ctx context.Context, vehicleID uuid.UUID) ([]VehicleProfileAnswer, error) {
	rows, err := q.db.Query(ctx, listVehicleProfileAnswers, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VehicleProfileAnswer{}
	for rows.Next() {
		var i VehicleProfileAnswer
		if err := rows.Scan(
			&i.VehicleID,
			&i.Question,
			&i.Answer,
			&i.Source,
			&i.AnsweredAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertVehicleProfileAnswer = `-- name: UpsertVehicleProfileAnswer :one

INSERT INTO vehicle_profile_answers (vehicle_id, question, answer, source)
VALUES ($1, $2, $3, $4)
ON CONFLICT (vehicle_id, question) DO UPDATE
SET answer      = EXCLUDED.answer,
    source      = EXCLUDED.source,
    answered_at = now()
RETURNING vehicle_id, question, answer, source, answered_at
`

type UpsertVehicleProfileAnswerParams struct {
	VehicleID uuid.UUID
	Question  string
	Answer    string
	Source    string
}

// What the owner told us about how their car is built.
//
// Small on purpose. This table exists for the one thing plans cannot express: that somebody
// was asked and answered "não sei". Without it the app has no way to tell "never asked"
// from "asked, and they do not know", so it asks forever.
func (q *Queries) UpsertVehicleProfileAnswer(ctx context.Context, arg UpsertVehicleProfileAnswerParams) (VehicleProfileAnswer, error) {
	row := q.db.QueryRow(ctx, upsertVehicleProfileAnswer,
		arg.VehicleID,
		arg.Question,
		arg.Answer,
		arg.Source,
	)
	var i VehicleProfileAnswer
	err := row.Scan(
		&i.VehicleID,
		&i.Question,
		&i.Answer,
		&i.Source,
		&i.AnsweredAt,
	)
	return i, err
}
