// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: records.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createMaintenanceOdometerReading = `-- name: CreateMaintenanceOdometerReading :exec
INSERT INTO odometer_readings (
    vehicle_id, mileage_km, occurred_on, source, recorded_by_user_id, source_maintenance_id
)
VALUES ($1, $2, $3, 'maintenance', $4, $5)
`

type CreateMaintenanceOdometerReadingParams struct {
	VehicleID           uuid.UUID
	MileageKm           int32
	OccurredOn          time.Time
	RecordedByUserID    *uuid.UUID
	SourceMaintenanceID *uuid.UUID
}

// Writes to odometer_readings from this module.
//
// odometer_readings is co-owned by design: the vehicle module owns manual readings and
// every read of the log, but any module may append a reading tagged with its own source,
// inside its own transaction. The alternative — calling the vehicle service — would put
// the reading outside the record's transaction and break the atomicity SPEC.md RN-01
// requires. The cache stays correct either way, because the trigger does not care who
// wrote the row.
func (q *Queries) CreateMaintenanceOdometerReading(ctx context.Context, arg CreateMaintenanceOdometerReadingParams) error {
	_, err := q.db.Exec(ctx, createMaintenanceOdometerReading,
		arg.VehicleID,
		arg.MileageKm,
		arg.OccurredOn,
		arg.RecordedByUserID,
		arg.SourceMaintenanceID,
	)
	return err
}

const createMaintenanceRecord = `-- name: CreateMaintenanceRecord :one
INSERT INTO maintenance_records (
    id, vehicle_id, occurred_on, mileage_km, kind,
    workshop_name, total_cost_cents, notes, recorded_by_user_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (id) DO NOTHING
RETURNING id, vehicle_id, occurred_on, mileage_km, kind, workshop_name, total_cost_cents, notes, recorded_by_user_id, created_at, updated_at, deleted_at
`

type CreateMaintenanceRecordParams struct {
	ID               uuid.UUID
	VehicleID        uuid.UUID
	OccurredOn       time.Time
	MileageKm        int32
	Kind             string
	WorkshopName     *string
	TotalCostCents   int64
	Notes            *string
	RecordedByUserID *uuid.UUID
}

func (q *Queries) CreateMaintenanceRecord(ctx context.Context, arg CreateMaintenanceRecordParams) (MaintenanceRecord, error) {
	row := q.db.QueryRow(ctx, createMaintenanceRecord,
		arg.ID,
		arg.VehicleID,
		arg.OccurredOn,
		arg.MileageKm,
		arg.Kind,
		arg.WorkshopName,
		arg.TotalCostCents,
		arg.Notes,
		arg.RecordedByUserID,
	)
	var i MaintenanceRecord
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.OccurredOn,
		&i.MileageKm,
		&i.Kind,
		&i.WorkshopName,
		&i.TotalCostCents,
		&i.Notes,
		&i.RecordedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createMaintenanceRecordItem = `-- name: CreateMaintenanceRecordItem :one
INSERT INTO maintenance_record_items (
    maintenance_record_id, maintenance_item_id,
    description, part_brand, cost_cents, warranty_months, warranty_km
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, maintenance_record_id, maintenance_item_id, description, part_brand, cost_cents, warranty_months, warranty_km, created_at
`

type CreateMaintenanceRecordItemParams struct {
	MaintenanceRecordID uuid.UUID
	MaintenanceItemID   uuid.UUID
	Description         *string
	PartBrand           *string
	CostCents           *int64
	WarrantyMonths      *int32
	WarrantyKm          *int32
}

func (q *Queries) CreateMaintenanceRecordItem(ctx context.Context, arg CreateMaintenanceRecordItemParams) (MaintenanceRecordItem, error) {
	row := q.db.QueryRow(ctx, createMaintenanceRecordItem,
		arg.MaintenanceRecordID,
		arg.MaintenanceItemID,
		arg.Description,
		arg.PartBrand,
		arg.CostCents,
		arg.WarrantyMonths,
		arg.WarrantyKm,
	)
	var i MaintenanceRecordItem
	err := row.Scan(
		&i.ID,
		&i.MaintenanceRecordID,
		&i.MaintenanceItemID,
		&i.Description,
		&i.PartBrand,
		&i.CostCents,
		&i.WarrantyMonths,
		&i.WarrantyKm,
		&i.CreatedAt,
	)
	return i, err
}

const deleteMaintenanceOdometerReading = `-- name: DeleteMaintenanceOdometerReading :exec
DELETE FROM odometer_readings WHERE source_maintenance_id = $1
`

func (q *Queries) DeleteMaintenanceOdometerReading(ctx context.Context, sourceMaintenanceID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteMaintenanceOdometerReading, sourceMaintenanceID)
	return err
}

const getMaintenanceRecordByID = `-- name: GetMaintenanceRecordByID :one
SELECT id, vehicle_id, occurred_on, mileage_km, kind, workshop_name, total_cost_cents, notes, recorded_by_user_id, created_at, updated_at, deleted_at FROM maintenance_records WHERE id = $1
`

// Used only on the idempotency path, immediately after an id conflict, and always with
// the caller's vehicle already authorised and the returned vehicle_id compared. It is not
// an authorisation bypass; every request-facing read uses the query below.
func (q *Queries) GetMaintenanceRecordByID(ctx context.Context, id uuid.UUID) (MaintenanceRecord, error) {
	row := q.db.QueryRow(ctx, getMaintenanceRecordByID, id)
	var i MaintenanceRecord
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.OccurredOn,
		&i.MileageKm,
		&i.Kind,
		&i.WorkshopName,
		&i.TotalCostCents,
		&i.Notes,
		&i.RecordedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getMaintenanceRecordForUser = `-- name: GetMaintenanceRecordForUser :one
SELECT r.id, r.vehicle_id, r.occurred_on, r.mileage_km, r.kind, r.workshop_name, r.total_cost_cents, r.notes, r.recorded_by_user_id, r.created_at, r.updated_at, r.deleted_at
FROM maintenance_records r
JOIN vehicle_ownerships o ON o.vehicle_id = r.vehicle_id
WHERE r.id = $1
  AND o.user_id = $2
  AND o.ended_on IS NULL
  AND r.deleted_at IS NULL
`

type GetMaintenanceRecordForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Records are read through the vehicle, never by id alone — the same rule as vehicles
// (SPEC.md RN-07). The join is the authorisation.
func (q *Queries) GetMaintenanceRecordForUser(ctx context.Context, arg GetMaintenanceRecordForUserParams) (MaintenanceRecord, error) {
	row := q.db.QueryRow(ctx, getMaintenanceRecordForUser, arg.ID, arg.UserID)
	var i MaintenanceRecord
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.OccurredOn,
		&i.MileageKm,
		&i.Kind,
		&i.WorkshopName,
		&i.TotalCostCents,
		&i.Notes,
		&i.RecordedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listLastPerformedByItem = `-- name: ListLastPerformedByItem :many
SELECT DISTINCT ON (ri.maintenance_item_id)
       ri.maintenance_item_id,
       r.id          AS record_id,
       r.occurred_on AS occurred_on,
       r.mileage_km  AS mileage_km
FROM maintenance_record_items ri
JOIN maintenance_records r ON r.id = ri.maintenance_record_id
WHERE r.vehicle_id = $1
  AND r.deleted_at IS NULL
ORDER BY ri.maintenance_item_id, r.occurred_on DESC, r.created_at DESC
`

type ListLastPerformedByItemRow struct {
	MaintenanceItemID uuid.UUID
	RecordID          uuid.UUID
	OccurredOn        time.Time
	MileageKm         int32
}

// The baseline for every plan on a vehicle: the most recent record naming each item.
//
// DISTINCT ON collapses to one row per item, and the ORDER BY inside it is exactly the
// rule from SPEC.md RN-02 — latest date wins, latest entry breaks the tie. Soft-deleted
// records are excluded, so retracting a service correctly moves the clock back.
//
// Keyed by item rather than by plan on purpose: a line inside a multi-item revisão must
// reset that item's clock just as a standalone record would.
func (q *Queries) ListLastPerformedByItem(ctx context.Context, vehicleID uuid.UUID) ([]ListLastPerformedByItemRow, error) {
	rows, err := q.db.Query(ctx, listLastPerformedByItem, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLastPerformedByItemRow{}
	for rows.Next() {
		var i ListLastPerformedByItemRow
		if err := rows.Scan(
			&i.MaintenanceItemID,
			&i.RecordID,
			&i.OccurredOn,
			&i.MileageKm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceRecordItems = `-- name: ListMaintenanceRecordItems :many
SELECT ri.id, ri.maintenance_record_id, ri.maintenance_item_id, ri.description, ri.part_brand, ri.cost_cents, ri.warranty_months, ri.warranty_km, ri.created_at, i.slug AS item_slug, i.name AS item_name, i.kind AS item_kind
FROM maintenance_record_items ri
JOIN maintenance_items i ON i.id = ri.maintenance_item_id
WHERE ri.maintenance_record_id = ANY($1::uuid[])
ORDER BY i.name
`

type ListMaintenanceRecordItemsRow struct {
	ID                  uuid.UUID
	MaintenanceRecordID uuid.UUID
	MaintenanceItemID   uuid.UUID
	Description         *string
	PartBrand           *string
	CostCents           *int64
	WarrantyMonths      *int32
	WarrantyKm          *int32
	CreatedAt           time.Time
	ItemSlug            string
	ItemName            string
	ItemKind            string
}

// One query for a whole page of records, rather than one per record: the N+1 here would
// be a page-sized burst of round trips for no reason.
func (q *Queries) ListMaintenanceRecordItems(ctx context.Context, recordIds []uuid.UUID) ([]ListMaintenanceRecordItemsRow, error) {
	rows, err := q.db.Query(ctx, listMaintenanceRecordItems, recordIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMaintenanceRecordItemsRow{}
	for rows.Next() {
		var i ListMaintenanceRecordItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.MaintenanceRecordID,
			&i.MaintenanceItemID,
			&i.Description,
			&i.PartBrand,
			&i.CostCents,
			&i.WarrantyMonths,
			&i.WarrantyKm,
			&i.CreatedAt,
			&i.ItemSlug,
			&i.ItemName,
			&i.ItemKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceRecordsForVehicle = `-- name: ListMaintenanceRecordsForVehicle :many
SELECT id, vehicle_id, occurred_on, mileage_km, kind, workshop_name, total_cost_cents, notes, recorded_by_user_id, created_at, updated_at, deleted_at
FROM maintenance_records
WHERE vehicle_id = $1
  AND deleted_at IS NULL
  AND (
        $2::date IS NULL
        OR (occurred_on, created_at, id) <
           ($2::date,
            $3::timestamptz,
            $4::uuid)
      )
ORDER BY occurred_on DESC, created_at DESC, id DESC
LIMIT $5
`

type ListMaintenanceRecordsForVehicleParams struct {
	VehicleID        uuid.UUID
	CursorOccurredOn *time.Time
	CursorCreatedAt  *time.Time
	CursorID         *uuid.UUID
	PageSize         int32
}

// Keyset pagination, newest first.
func (q *Queries) ListMaintenanceRecordsForVehicle(ctx context.Context, arg ListMaintenanceRecordsForVehicleParams) ([]MaintenanceRecord, error) {
	rows, err := q.db.Query(ctx, listMaintenanceRecordsForVehicle,
		arg.VehicleID,
		arg.CursorOccurredOn,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MaintenanceRecord{}
	for rows.Next() {
		var i MaintenanceRecord
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.OccurredOn,
			&i.MileageKm,
			&i.Kind,
			&i.WorkshopName,
			&i.TotalCostCents,
			&i.Notes,
			&i.RecordedByUserID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWarrantiesForVehicle = `-- name: ListWarrantiesForVehicle :many
SELECT ri.id,
       ri.maintenance_item_id,
       ri.warranty_months,
       ri.warranty_km,
       i.name        AS item_name,
       r.id          AS record_id,
       r.occurred_on AS record_occurred_on,
       r.mileage_km  AS record_mileage_km
FROM maintenance_record_items ri
JOIN maintenance_records r ON r.id = ri.maintenance_record_id
JOIN maintenance_items i ON i.id = ri.maintenance_item_id
WHERE r.vehicle_id = $1
  AND r.deleted_at IS NULL
  AND (ri.warranty_months IS NOT NULL OR ri.warranty_km IS NOT NULL)
ORDER BY r.occurred_on DESC
`

type ListWarrantiesForVehicleRow struct {
	ID                uuid.UUID
	MaintenanceItemID uuid.UUID
	WarrantyMonths    *int32
	WarrantyKm        *int32
	ItemName          string
	RecordID          uuid.UUID
	RecordOccurredOn  time.Time
	RecordMileageKm   int32
}

// Every line item that carries a warranty, with the record's date and mileage so the
// expiry can be derived. Warranty end is never stored (SPEC.md RN-05).
func (q *Queries) ListWarrantiesForVehicle(ctx context.Context, vehicleID uuid.UUID) ([]ListWarrantiesForVehicleRow, error) {
	rows, err := q.db.Query(ctx, listWarrantiesForVehicle, vehicleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListWarrantiesForVehicleRow{}
	for rows.Next() {
		var i ListWarrantiesForVehicleRow
		if err := rows.Scan(
			&i.ID,
			&i.MaintenanceItemID,
			&i.WarrantyMonths,
			&i.WarrantyKm,
			&i.ItemName,
			&i.RecordID,
			&i.RecordOccurredOn,
			&i.RecordMileageKm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteMaintenanceRecord = `-- name: SoftDeleteMaintenanceRecord :execrows
UPDATE maintenance_records
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

// Soft delete: a service record is the product's asset at resale, and one mistaken tap
// must not destroy it.
func (q *Queries) SoftDeleteMaintenanceRecord(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteMaintenanceRecord, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateMaintenanceOdometerReading = `-- name: UpdateMaintenanceOdometerReading :exec
UPDATE odometer_readings
SET mileage_km = $2, occurred_on = $3
WHERE source_maintenance_id = $1
`

type UpdateMaintenanceOdometerReadingParams struct {
	SourceMaintenanceID *uuid.UUID
	MileageKm           int32
	OccurredOn          time.Time
}

func (q *Queries) UpdateMaintenanceOdometerReading(ctx context.Context, arg UpdateMaintenanceOdometerReadingParams) error {
	_, err := q.db.Exec(ctx, updateMaintenanceOdometerReading, arg.SourceMaintenanceID, arg.MileageKm, arg.OccurredOn)
	return err
}

const updateMaintenanceRecord = `-- name: UpdateMaintenanceRecord :one
UPDATE maintenance_records
SET occurred_on      = COALESCE($1, occurred_on),
    mileage_km       = COALESCE($2, mileage_km),
    workshop_name    = COALESCE($3, workshop_name),
    total_cost_cents = COALESCE($4, total_cost_cents),
    notes            = COALESCE($5, notes),
    updated_at       = now()
WHERE id = $6 AND deleted_at IS NULL
RETURNING id, vehicle_id, occurred_on, mileage_km, kind, workshop_name, total_cost_cents, notes, recorded_by_user_id, created_at, updated_at, deleted_at
`

type UpdateMaintenanceRecordParams struct {
	OccurredOn     *time.Time
	MileageKm      *int32
	WorkshopName   *string
	TotalCostCents *int64
	Notes          *string
	ID             uuid.UUID
}

func (q *Queries) UpdateMaintenanceRecord(ctx context.Context, arg UpdateMaintenanceRecordParams) (MaintenanceRecord, error) {
	row := q.db.QueryRow(ctx, updateMaintenanceRecord,
		arg.OccurredOn,
		arg.MileageKm,
		arg.WorkshopName,
		arg.TotalCostCents,
		arg.Notes,
		arg.ID,
	)
	var i MaintenanceRecord
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.OccurredOn,
		&i.MileageKm,
		&i.Kind,
		&i.WorkshopName,
		&i.TotalCostCents,
		&i.Notes,
		&i.RecordedByUserID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
