// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: odometer.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const createOdometerReading = `-- name: CreateOdometerReading :one
INSERT INTO odometer_readings (
    id, vehicle_id, mileage_km, occurred_on, source, recorded_by_user_id, notes
)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (id) DO NOTHING
RETURNING id, vehicle_id, mileage_km, occurred_on, source, recorded_by_user_id, notes, created_at, source_maintenance_id
`

type CreateOdometerReadingParams struct {
	ID               uuid.UUID
	VehicleID        uuid.UUID
	MileageKm        int32
	OccurredOn       time.Time
	Source           string
	RecordedByUserID *uuid.UUID
	Notes            *string
}

func (q *Queries) CreateOdometerReading(ctx context.Context, arg CreateOdometerReadingParams) (OdometerReading, error) {
	row := q.db.QueryRow(ctx, createOdometerReading,
		arg.ID,
		arg.VehicleID,
		arg.MileageKm,
		arg.OccurredOn,
		arg.Source,
		arg.RecordedByUserID,
		arg.Notes,
	)
	var i OdometerReading
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.MileageKm,
		&i.OccurredOn,
		&i.Source,
		&i.RecordedByUserID,
		&i.Notes,
		&i.CreatedAt,
		&i.SourceMaintenanceID,
	)
	return i, err
}

const deleteOdometerReading = `-- name: DeleteOdometerReading :execrows
DELETE FROM odometer_readings WHERE id = $1
`

func (q *Queries) DeleteOdometerReading(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOdometerReading, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getNextOdometerReading = `-- name: GetNextOdometerReading :one
SELECT id, vehicle_id, mileage_km, occurred_on, source, recorded_by_user_id, notes, created_at, source_maintenance_id
FROM odometer_readings
WHERE vehicle_id = $1
  AND occurred_on > $2
ORDER BY occurred_on ASC, created_at ASC
LIMIT 1
`

type GetNextOdometerReadingParams struct {
	VehicleID  uuid.UUID
	OccurredOn time.Time
}

func (q *Queries) GetNextOdometerReading(ctx context.Context, arg GetNextOdometerReadingParams) (OdometerReading, error) {
	row := q.db.QueryRow(ctx, getNextOdometerReading, arg.VehicleID, arg.OccurredOn)
	var i OdometerReading
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.MileageKm,
		&i.OccurredOn,
		&i.Source,
		&i.RecordedByUserID,
		&i.Notes,
		&i.CreatedAt,
		&i.SourceMaintenanceID,
	)
	return i, err
}

const getOdometerReading = `-- name: GetOdometerReading :one
SELECT id, vehicle_id, mileage_km, occurred_on, source, recorded_by_user_id, notes, created_at, source_maintenance_id FROM odometer_readings WHERE id = $1
`

func (q *Queries) GetOdometerReading(ctx context.Context, id uuid.UUID) (OdometerReading, error) {
	row := q.db.QueryRow(ctx, getOdometerReading, id)
	var i OdometerReading
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.MileageKm,
		&i.OccurredOn,
		&i.Source,
		&i.RecordedByUserID,
		&i.Notes,
		&i.CreatedAt,
		&i.SourceMaintenanceID,
	)
	return i, err
}

const getPreviousOdometerReading = `-- name: GetPreviousOdometerReading :one

SELECT id, vehicle_id, mileage_km, occurred_on, source, recorded_by_user_id, notes, created_at, source_maintenance_id
FROM odometer_readings
WHERE vehicle_id = $1
  AND occurred_on <= $2
ORDER BY occurred_on DESC, created_at DESC
LIMIT 1
`

type GetPreviousOdometerReadingParams struct {
	VehicleID  uuid.UUID
	OccurredOn time.Time
}

// The monotonicity check for a new reading (SPEC.md RN-01).
//
// It compares against the reading's NEIGHBOURS IN TIME, not against the vehicle's current
// mileage. That difference matters: someone entering a reading they forgot three months
// ago is legitimately recording a lower number, and comparing against "current" would
// reject it. What is actually invalid is a reading that contradicts the entries around it.
//
// Two queries rather than one with scalar subqueries: sqlc infers a scalar subquery as
// NOT NULL, which is wrong here — a vehicle's first reading has no neighbour on either
// side, and scanning that NULL into an int32 fails at runtime. Splitting them makes
// "no neighbour" an unambiguous pgx.ErrNoRows.
func (q *Queries) GetPreviousOdometerReading(ctx context.Context, arg GetPreviousOdometerReadingParams) (OdometerReading, error) {
	row := q.db.QueryRow(ctx, getPreviousOdometerReading, arg.VehicleID, arg.OccurredOn)
	var i OdometerReading
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.MileageKm,
		&i.OccurredOn,
		&i.Source,
		&i.RecordedByUserID,
		&i.Notes,
		&i.CreatedAt,
		&i.SourceMaintenanceID,
	)
	return i, err
}

const listOdometerReadings = `-- name: ListOdometerReadings :many
SELECT id, vehicle_id, mileage_km, occurred_on, source, recorded_by_user_id, notes, created_at, source_maintenance_id
FROM odometer_readings
WHERE vehicle_id = $1
  AND (
        $2::date IS NULL
        OR (occurred_on, created_at, id) <
           ($2::date,
            $3::timestamptz,
            $4::uuid)
      )
ORDER BY occurred_on DESC, created_at DESC, id DESC
LIMIT $5
`

type ListOdometerReadingsParams struct {
	VehicleID        uuid.UUID
	CursorOccurredOn *time.Time
	CursorCreatedAt  *time.Time
	CursorID         *uuid.UUID
	PageSize         int32
}

// Keyset pagination, never OFFSET: readings are appended constantly, and an offset page
// silently skips or repeats rows whenever something is inserted between two requests.
func (q *Queries) ListOdometerReadings(ctx context.Context, arg ListOdometerReadingsParams) ([]OdometerReading, error) {
	rows, err := q.db.Query(ctx, listOdometerReadings,
		arg.VehicleID,
		arg.CursorOccurredOn,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OdometerReading{}
	for rows.Next() {
		var i OdometerReading
		if err := rows.Scan(
			&i.ID,
			&i.VehicleID,
			&i.MileageKm,
			&i.OccurredOn,
			&i.Source,
			&i.RecordedByUserID,
			&i.Notes,
			&i.CreatedAt,
			&i.SourceMaintenanceID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
