// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: vehicles.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const createOwnership = `-- name: CreateOwnership :one
INSERT INTO vehicle_ownerships (vehicle_id, user_id, role, started_on)
VALUES ($1, $2, 'owner', CURRENT_DATE)
RETURNING id, vehicle_id, user_id, role, started_on, ended_on, created_at
`

type CreateOwnershipParams struct {
	VehicleID uuid.UUID
	UserID    uuid.UUID
}

func (q *Queries) CreateOwnership(ctx context.Context, arg CreateOwnershipParams) (VehicleOwnership, error) {
	row := q.db.QueryRow(ctx, createOwnership, arg.VehicleID, arg.UserID)
	var i VehicleOwnership
	err := row.Scan(
		&i.ID,
		&i.VehicleID,
		&i.UserID,
		&i.Role,
		&i.StartedOn,
		&i.EndedOn,
		&i.CreatedAt,
	)
	return i, err
}

const createVehicle = `-- name: CreateVehicle :one
INSERT INTO vehicles (
    id, vehicle_type, brand, model, version,
    manufacture_year, model_year, plate, renavam, chassis,
    fuel_type, color, nickname, fipe_code,
    -- The link to the catalogue entry the owner picked. Always nullable: a vehicle typed
    -- in by hand is still a vehicle, and the app already installed never sends these.
    catalog_brand_id, catalog_model_id, catalog_model_year_id
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15, $16, $17)
ON CONFLICT (id) DO NOTHING
RETURNING vehicle_type, id, brand, model, version, manufacture_year, model_year, plate, renavam, chassis, fuel_type, color, nickname, fipe_code, current_mileage_km, current_mileage_at, created_at, updated_at, deleted_at, catalog_brand_id, catalog_model_id, catalog_model_year_id
`

type CreateVehicleParams struct {
	ID                 uuid.UUID
	VehicleType        string
	Brand              string
	Model              string
	Version            *string
	ManufactureYear    *int32
	ModelYear          *int32
	Plate              *string
	Renavam            *string
	Chassis            *string
	FuelType           *string
	Color              *string
	Nickname           *string
	FipeCode           *string
	CatalogBrandID     *uuid.UUID
	CatalogModelID     *uuid.UUID
	CatalogModelYearID *uuid.UUID
}

// The id comes from the client (UUIDv7). ON CONFLICT DO NOTHING makes a retried create
// idempotent: a mobile client that loses signal mid-request can safely send it again.
func (q *Queries) CreateVehicle(ctx context.Context, arg CreateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, createVehicle,
		arg.ID,
		arg.VehicleType,
		arg.Brand,
		arg.Model,
		arg.Version,
		arg.ManufactureYear,
		arg.ModelYear,
		arg.Plate,
		arg.Renavam,
		arg.Chassis,
		arg.FuelType,
		arg.Color,
		arg.Nickname,
		arg.FipeCode,
		arg.CatalogBrandID,
		arg.CatalogModelID,
		arg.CatalogModelYearID,
	)
	var i Vehicle
	err := row.Scan(
		&i.VehicleType,
		&i.ID,
		&i.Brand,
		&i.Model,
		&i.Version,
		&i.ManufactureYear,
		&i.ModelYear,
		&i.Plate,
		&i.Renavam,
		&i.Chassis,
		&i.FuelType,
		&i.Color,
		&i.Nickname,
		&i.FipeCode,
		&i.CurrentMileageKm,
		&i.CurrentMileageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CatalogBrandID,
		&i.CatalogModelID,
		&i.CatalogModelYearID,
	)
	return i, err
}

const deleteVehiclesOwnedSolelyBy = `-- name: DeleteVehiclesOwnedSolelyBy :execrows

DELETE FROM vehicles v
WHERE EXISTS (
        SELECT 1 FROM vehicle_ownerships o
        WHERE o.vehicle_id = v.id AND o.user_id = $1 AND o.ended_on IS NULL
      )
  AND NOT EXISTS (
        SELECT 1 FROM vehicle_ownerships o2
        WHERE o2.vehicle_id = v.id AND o2.user_id <> $1 AND o2.ended_on IS NULL
      )
`

// There is no query here that refreshes vehicles.current_mileage_km. The invariant is
// enforced by a trigger on odometer_readings (migration 000006), because more than one
// module writes readings and a module that forgets to refresh would silently serve a
// stale mileage rather than fail.
// LGPD erasure. Removes vehicles this user owns and nobody else does, including
// soft-deleted ones; everything else cascades from vehicles.
//
// The NOT EXISTS clause is inert today (a vehicle has one owner) and is what keeps this
// correct once a vehicle can be shared: erasing one person must not delete the co-owner's
// car.
func (q *Queries) DeleteVehiclesOwnedSolelyBy(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, deleteVehiclesOwnedSolelyBy, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getVehicleForUser = `-- name: GetVehicleForUser :one
SELECT v.vehicle_type, v.id, v.brand, v.model, v.version, v.manufacture_year, v.model_year, v.plate, v.renavam, v.chassis, v.fuel_type, v.color, v.nickname, v.fipe_code, v.current_mileage_km, v.current_mileage_at, v.created_at, v.updated_at, v.deleted_at, v.catalog_brand_id, v.catalog_model_id, v.catalog_model_year_id
FROM vehicles v
JOIN vehicle_ownerships o ON o.vehicle_id = v.id
WHERE v.id = $1
  AND o.user_id = $2
  AND o.ended_on IS NULL
  AND v.deleted_at IS NULL
`

type GetVehicleForUserParams struct {
	ID     uuid.UUID
	UserID uuid.UUID
}

// Every read of a vehicle goes through ownership. There is no query in this module that
// fetches a vehicle by id alone (SPEC.md RN-07).
func (q *Queries) GetVehicleForUser(ctx context.Context, arg GetVehicleForUserParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, getVehicleForUser, arg.ID, arg.UserID)
	var i Vehicle
	err := row.Scan(
		&i.VehicleType,
		&i.ID,
		&i.Brand,
		&i.Model,
		&i.Version,
		&i.ManufactureYear,
		&i.ModelYear,
		&i.Plate,
		&i.Renavam,
		&i.Chassis,
		&i.FuelType,
		&i.Color,
		&i.Nickname,
		&i.FipeCode,
		&i.CurrentMileageKm,
		&i.CurrentMileageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CatalogBrandID,
		&i.CatalogModelID,
		&i.CatalogModelYearID,
	)
	return i, err
}

const listVehiclesForUser = `-- name: ListVehiclesForUser :many
SELECT v.vehicle_type, v.id, v.brand, v.model, v.version, v.manufacture_year, v.model_year, v.plate, v.renavam, v.chassis, v.fuel_type, v.color, v.nickname, v.fipe_code, v.current_mileage_km, v.current_mileage_at, v.created_at, v.updated_at, v.deleted_at, v.catalog_brand_id, v.catalog_model_id, v.catalog_model_year_id
FROM vehicles v
JOIN vehicle_ownerships o ON o.vehicle_id = v.id
WHERE o.user_id = $1
  AND o.ended_on IS NULL
  AND v.deleted_at IS NULL
ORDER BY v.created_at ASC
`

func (q *Queries) ListVehiclesForUser(ctx context.Context, userID uuid.UUID) ([]Vehicle, error) {
	rows, err := q.db.Query(ctx, listVehiclesForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Vehicle{}
	for rows.Next() {
		var i Vehicle
		if err := rows.Scan(
			&i.VehicleType,
			&i.ID,
			&i.Brand,
			&i.Model,
			&i.Version,
			&i.ManufactureYear,
			&i.ModelYear,
			&i.Plate,
			&i.Renavam,
			&i.Chassis,
			&i.FuelType,
			&i.Color,
			&i.Nickname,
			&i.FipeCode,
			&i.CurrentMileageKm,
			&i.CurrentMileageAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.CatalogBrandID,
			&i.CatalogModelID,
			&i.CatalogModelYearID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteVehicle = `-- name: SoftDeleteVehicle :execrows
UPDATE vehicles
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

// Soft delete: the service history is the product's asset, and one mistaken tap must not
// destroy years of it.
func (q *Queries) SoftDeleteVehicle(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteVehicle, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateVehicle = `-- name: UpdateVehicle :one
UPDATE vehicles
SET brand            = COALESCE($1, brand),
    model            = COALESCE($2, model),
    version          = CASE WHEN 'version' = ANY($3::text[]) THEN NULL
                            ELSE COALESCE($4, version) END,
    manufacture_year = CASE WHEN 'manufacture_year' = ANY($3::text[]) THEN NULL
                            ELSE COALESCE($5, manufacture_year) END,
    model_year       = CASE WHEN 'model_year' = ANY($3::text[]) THEN NULL
                            ELSE COALESCE($6, model_year) END,
    plate            = CASE WHEN 'plate' = ANY($3::text[]) THEN NULL
                            ELSE COALESCE($7, plate) END,
    renavam          = CASE WHEN 'renavam' = ANY($3::text[]) THEN NULL
                            ELSE COALESCE($8, renavam) END,
    chassis          = CASE WHEN 'chassis' = ANY($3::text[]) THEN NULL
                            ELSE COALESCE($9, chassis) END,
    fuel_type        = CASE WHEN 'fuel_type' = ANY($3::text[]) THEN NULL
                            ELSE COALESCE($10, fuel_type) END,
    color            = CASE WHEN 'color' = ANY($3::text[]) THEN NULL
                            ELSE COALESCE($11, color) END,
    nickname         = CASE WHEN 'nickname' = ANY($3::text[]) THEN NULL
                            ELSE COALESCE($12, nickname) END,
    fipe_code        = CASE WHEN 'fipe_code' = ANY($3::text[]) THEN NULL
                            ELSE COALESCE($13, fipe_code) END,

    -- The three move together or not at all. They are resolved from a single
    -- catalog_model_year_id, so a partial update could not produce a brand that disagrees
    -- with its model — but writing them as one group is what keeps that true if somebody
    -- later adds a second way in.
    catalog_brand_id      = COALESCE($14, catalog_brand_id),
    catalog_model_id      = COALESCE($15, catalog_model_id),
    catalog_model_year_id = COALESCE($16, catalog_model_year_id),

    updated_at       = now()
WHERE id = $17 AND deleted_at IS NULL
RETURNING vehicle_type, id, brand, model, version, manufacture_year, model_year, plate, renavam, chassis, fuel_type, color, nickname, fipe_code, current_mileage_km, current_mileage_at, created_at, updated_at, deleted_at, catalog_brand_id, catalog_model_id, catalog_model_year_id
`

type UpdateVehicleParams struct {
	Brand              *string
	Model              *string
	Clear              []string
	Version            *string
	ManufactureYear    *int32
	ModelYear          *int32
	Plate              *string
	Renavam            *string
	Chassis            *string
	FuelType           *string
	Color              *string
	Nickname           *string
	FipeCode           *string
	CatalogBrandID     *uuid.UUID
	CatalogModelID     *uuid.UUID
	CatalogModelYearID *uuid.UUID
	ID                 uuid.UUID
}

// PATCH semantics: a NULL argument leaves the column untouched. Optional columns named
// in `clear` are set back to NULL. brand and model are NOT NULL and are not accepted
// there — emptying them is not an edit, it is destroying the identity of the car.
func (q *Queries) UpdateVehicle(ctx context.Context, arg UpdateVehicleParams) (Vehicle, error) {
	row := q.db.QueryRow(ctx, updateVehicle,
		arg.Brand,
		arg.Model,
		arg.Clear,
		arg.Version,
		arg.ManufactureYear,
		arg.ModelYear,
		arg.Plate,
		arg.Renavam,
		arg.Chassis,
		arg.FuelType,
		arg.Color,
		arg.Nickname,
		arg.FipeCode,
		arg.CatalogBrandID,
		arg.CatalogModelID,
		arg.CatalogModelYearID,
		arg.ID,
	)
	var i Vehicle
	err := row.Scan(
		&i.VehicleType,
		&i.ID,
		&i.Brand,
		&i.Model,
		&i.Version,
		&i.ManufactureYear,
		&i.ModelYear,
		&i.Plate,
		&i.Renavam,
		&i.Chassis,
		&i.FuelType,
		&i.Color,
		&i.Nickname,
		&i.FipeCode,
		&i.CurrentMileageKm,
		&i.CurrentMileageAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.CatalogBrandID,
		&i.CatalogModelID,
		&i.CatalogModelYearID,
	)
	return i, err
}
