// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timeline.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listVehicleTimeline = `-- name: ListVehicleTimeline :many

WITH entries AS (
    -- NULLABILITY WARNING (SPEC.md D-09: sqlc guarantees types, not semantics).
    --
    -- sqlc infers a UNION column's nullability from the FIRST branch. This branch has NOT
    -- NULL columns where the branches below select NULL, so the generated struct would use
    -- int64/int32 and every odometer or obligation row would fail to scan at runtime.
    -- Casting in SQL does not fix it — that was tried. What fixes it is the per-column
    -- override on entries.title / amount_cents / mileage_km / care in sqlc.yaml.
    --
    -- If you add a branch to this UNION with a column that can be NULL, check the
    -- generated struct. ` + "`" + `care` + "`" + ` is nullable on the odometer and obligation branches, so
    -- it has an override on entries.care in sqlc.yaml (pointer: true).
    SELECT 'manutencao'::text AS kind,
           r.id,
           r.occurred_on,
           r.created_at,
           (SELECT string_agg(i.name, ', ' ORDER BY i.name)
              FROM maintenance_record_items ri
              JOIN maintenance_items i ON i.id = ri.maintenance_item_id
             WHERE ri.maintenance_record_id = r.id) AS title,
           r.workshop_name                          AS subtitle,
           -- The total when the owner typed one, otherwise what the lines add up to. A
           -- record with R$ 450 on its lines and no total used to show no amount at all.
           CASE WHEN r.total_cost_cents > 0 THEN r.total_cost_cents
                ELSE (SELECT SUM(ri.cost_cents)
                        FROM maintenance_record_items ri
                       WHERE ri.maintenance_record_id = r.id)
           END::bigint                              AS amount_cents,
           r.mileage_km                             AS mileage_km,
           (SELECT bool_and(i.kind = 'care')
              FROM maintenance_record_items ri
              JOIN maintenance_items i ON i.id = ri.maintenance_item_id
             WHERE ri.maintenance_record_id = r.id) AS care
    FROM maintenance_records r
    WHERE r.vehicle_id = $5
      AND r.deleted_at IS NULL

    UNION ALL

    SELECT 'odometro'::text,
           o.id,
           o.occurred_on,
           o.created_at,
           NULL::text,
           -- Words for a person, not the column value: "manual" says nothing a reading
           -- does not already say, and "correction" reached the screen in English.
           CASE o.source WHEN 'correction' THEN 'Correção' END,
           NULL::bigint,
           o.mileage_km,
           NULL::boolean
    FROM odometer_readings o
    WHERE o.vehicle_id = $5
      AND o.source_maintenance_id IS NULL
      AND o.source_abastecimento_id IS NULL

    UNION ALL

    SELECT 'abastecimento'::text,
           a.id,
           a.occurred_on,
           a.created_at,
           NULL::text,
           a.fuel,
           a.total_cost_cents,
           a.mileage_km,
           NULL::boolean
    FROM abastecimentos a
    WHERE a.vehicle_id = $5

    UNION ALL

    SELECT ob.kind,
           ob.id,
           ob.paid_on,
           ob.created_at,
           NULL::text,
           ob.reference_year::text,
           -- Paid without saying how much: the amount it was due for is the best figure
           -- there is, and nothing at all made a paid IPVA cost R$ 0,00.
           COALESCE(ob.paid_amount_cents, ob.amount_cents),
           NULL::integer,
           NULL::boolean
    FROM vehicle_obligations ob
    WHERE ob.vehicle_id = $5
      AND ob.paid_on IS NOT NULL
)
SELECT kind, id, occurred_on, created_at, title, subtitle, amount_cents, mileage_km, care
FROM entries
WHERE (
        $1::date IS NULL
        OR (occurred_on, created_at, id) <
           ($1::date,
            $2::timestamptz,
            $3::uuid)
      )
ORDER BY occurred_on DESC, created_at DESC, id DESC
LIMIT $4
`

type ListVehicleTimelineParams struct {
	CursorOccurredOn *time.Time
	CursorCreatedAt  *time.Time
	CursorID         *uuid.UUID
	PageSize         int32
	VehicleID        uuid.UUID
}

type ListVehicleTimelineRow struct {
	Kind        string
	ID          uuid.UUID
	OccurredOn  time.Time
	CreatedAt   time.Time
	Title       *string
	Subtitle    *string
	AmountCents *int64
	MileageKm   *int32
	Care        *bool
}

// The insight module is a READ MODEL. Every query here is read-only and crosses module
// boundaries deliberately (SPEC.md section 5): a unified timeline cannot be assembled from
// three separate paginated endpoints without pulling the whole history into memory.
// One heterogeneous history, newest first, keyset-paginated.
//
// The UNION is what makes pagination correct: ordering and cursoring happen over the
// combined set, so a page boundary never falls between two sources.
//
// Odometer readings produced BY a maintenance or an abastecimento are excluded — they
// would appear twice, once as the event and once as the reading it generated.
func (q *Queries) ListVehicleTimeline(ctx context.Context, arg ListVehicleTimelineParams) ([]ListVehicleTimelineRow, error) {
	rows, err := q.db.Query(ctx, listVehicleTimeline,
		arg.CursorOccurredOn,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
		arg.VehicleID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVehicleTimelineRow{}
	for rows.Next() {
		var i ListVehicleTimelineRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.OccurredOn,
			&i.CreatedAt,
			&i.Title,
			&i.Subtitle,
			&i.AmountCents,
			&i.MileageKm,
			&i.Care,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumVehicleCosts = `-- name: SumVehicleCosts :one
SELECT
    -- Same rule as the timeline row: the typed total, or the sum of the lines when no total
    -- was given. The two must agree, or the history and the cost screen tell different
    -- stories about the same service.
    COALESCE((SELECT SUM(CASE WHEN r.total_cost_cents > 0 THEN r.total_cost_cents
                              ELSE COALESCE((SELECT SUM(ri.cost_cents)
                                               FROM maintenance_record_items ri
                                              WHERE ri.maintenance_record_id = r.id), 0)
                         END)
                FROM maintenance_records r
               WHERE r.vehicle_id = $1
                 AND r.deleted_at IS NULL
                 AND r.occurred_on >= $2), 0)::bigint AS maintenance_cents,

    COALESCE((SELECT SUM(COALESCE(ob.paid_amount_cents, ob.amount_cents))
                FROM vehicle_obligations ob
               WHERE ob.vehicle_id = $1
                 AND ob.paid_on IS NOT NULL
                 AND ob.paid_on >= $2), 0)::bigint AS obligations_cents,

    COALESCE((SELECT SUM(s.premium_cents)
                FROM seguros s
               WHERE s.vehicle_id = $1
                 AND s.starts_on >= $2), 0)::bigint AS seguro_cents,

    COALESCE((SELECT SUM(a.total_cost_cents)
                FROM abastecimentos a
               WHERE a.vehicle_id = $1
                 AND a.occurred_on >= $2), 0)::bigint AS abastecimento_cents
`

type SumVehicleCostsParams struct {
	VehicleID uuid.UUID
	Since     time.Time
}

type SumVehicleCostsRow struct {
	MaintenanceCents   int64
	ObligationsCents   int64
	SeguroCents        int64
	AbastecimentoCents int64
}

// Costs actually recorded, by category, since a cut-off date.
//
// COALESCE makes every column genuinely NOT NULL, so a vehicle with no history reports
// zeros instead of nulls the client has to special-case.
//
// abastecimento_cents is summed here but must NOT be folded into tracked_cents — that
// field is frozen for the published app (see dashboardCosts in dto.go).
func (q *Queries) SumVehicleCosts(ctx context.Context, arg SumVehicleCostsParams) (SumVehicleCostsRow, error) {
	row := q.db.QueryRow(ctx, sumVehicleCosts, arg.VehicleID, arg.Since)
	var i SumVehicleCostsRow
	err := row.Scan(
		&i.MaintenanceCents,
		&i.ObligationsCents,
		&i.SeguroCents,
		&i.AbastecimentoCents,
	)
	return i, err
}
