// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: timeline.sql

package db

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const listVehicleTimeline = `-- name: ListVehicleTimeline :many

WITH entries AS (
    -- The explicit casts and the CASE wrappers are not decoration. sqlc infers a UNION
    -- column's nullability from the FIRST branch, and here that branch has NOT NULL
    -- columns while the others select NULL. Without these, the generated struct would use
    -- int64/int32 and every odometer or obligation row would fail to scan at runtime —
    -- exactly the class of bug SPEC.md D-09 warns about (sqlc guarantees types, not
    -- semantics). The string_agg cast is for the same reason: untyped, it generates []byte.
    SELECT 'manutencao'::text AS kind,
           r.id,
           r.occurred_on,
           r.created_at,
           (SELECT string_agg(i.name, ', ' ORDER BY i.name)
              FROM maintenance_record_items ri
              JOIN maintenance_items i ON i.id = ri.maintenance_item_id
             WHERE ri.maintenance_record_id = r.id)::text  AS title,
           r.workshop_name                                 AS subtitle,
           (CASE WHEN TRUE THEN r.total_cost_cents END)::bigint  AS amount_cents,
           (CASE WHEN TRUE THEN r.mileage_km END)::integer       AS mileage_km
    FROM maintenance_records r
    WHERE r.vehicle_id = $5
      AND r.deleted_at IS NULL

    UNION ALL

    SELECT 'odometro'::text,
           o.id,
           o.occurred_on,
           o.created_at,
           NULL::text,
           o.source,
           NULL::bigint,
           o.mileage_km
    FROM odometer_readings o
    WHERE o.vehicle_id = $5
      AND o.source_maintenance_id IS NULL

    UNION ALL

    SELECT ob.kind,
           ob.id,
           ob.paid_on,
           ob.created_at,
           NULL::text,
           ob.reference_year::text,
           ob.paid_amount_cents,
           NULL::integer
    FROM vehicle_obligations ob
    WHERE ob.vehicle_id = $5
      AND ob.paid_on IS NOT NULL
)
SELECT kind, id, occurred_on, created_at, title, subtitle, amount_cents, mileage_km
FROM entries
WHERE (
        $1::date IS NULL
        OR (occurred_on, created_at, id) <
           ($1::date,
            $2::timestamptz,
            $3::uuid)
      )
ORDER BY occurred_on DESC, created_at DESC, id DESC
LIMIT $4
`

type ListVehicleTimelineParams struct {
	CursorOccurredOn *time.Time
	CursorCreatedAt  *time.Time
	CursorID         *uuid.UUID
	PageSize         int32
	VehicleID        uuid.UUID
}

type ListVehicleTimelineRow struct {
	Kind        string
	ID          uuid.UUID
	OccurredOn  time.Time
	CreatedAt   time.Time
	Title       *string
	Subtitle    *string
	AmountCents *int64
	MileageKm   *int32
}

// The insight module is a READ MODEL. Every query here is read-only and crosses module
// boundaries deliberately (SPEC.md section 5): a unified timeline cannot be assembled from
// three separate paginated endpoints without pulling the whole history into memory.
// One heterogeneous history, newest first, keyset-paginated.
//
// The UNION is what makes pagination correct: ordering and cursoring happen over the
// combined set, so a page boundary never falls between two sources.
//
// Odometer readings produced BY a maintenance are excluded — they would appear twice, once
// as the service and once as the reading it generated.
func (q *Queries) ListVehicleTimeline(ctx context.Context, arg ListVehicleTimelineParams) ([]ListVehicleTimelineRow, error) {
	rows, err := q.db.Query(ctx, listVehicleTimeline,
		arg.CursorOccurredOn,
		arg.CursorCreatedAt,
		arg.CursorID,
		arg.PageSize,
		arg.VehicleID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListVehicleTimelineRow{}
	for rows.Next() {
		var i ListVehicleTimelineRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.OccurredOn,
			&i.CreatedAt,
			&i.Title,
			&i.Subtitle,
			&i.AmountCents,
			&i.MileageKm,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const sumVehicleCosts = `-- name: SumVehicleCosts :one
SELECT
    COALESCE((SELECT SUM(r.total_cost_cents)
                FROM maintenance_records r
               WHERE r.vehicle_id = $1
                 AND r.deleted_at IS NULL
                 AND r.occurred_on >= $2), 0)::bigint AS maintenance_cents,

    COALESCE((SELECT SUM(ob.paid_amount_cents)
                FROM vehicle_obligations ob
               WHERE ob.vehicle_id = $1
                 AND ob.paid_on IS NOT NULL
                 AND ob.paid_on >= $2), 0)::bigint AS obligations_cents,

    COALESCE((SELECT SUM(s.premium_cents)
                FROM seguros s
               WHERE s.vehicle_id = $1
                 AND s.starts_on >= $2), 0)::bigint AS seguro_cents
`

type SumVehicleCostsParams struct {
	VehicleID uuid.UUID
	Since     time.Time
}

type SumVehicleCostsRow struct {
	MaintenanceCents int64
	ObligationsCents int64
	SeguroCents      int64
}

// Costs actually recorded, by category, since a cut-off date.
//
// NOT a running cost: fuel and general expenses do not exist yet (SPEC.md, MVP-1 scope), so
// the response names exactly which categories are counted rather than presenting a total
// the owner would read as complete.
//
// COALESCE makes every column genuinely NOT NULL, so a vehicle with no history reports
// zeros instead of nulls the client has to special-case.
func (q *Queries) SumVehicleCosts(ctx context.Context, arg SumVehicleCostsParams) (SumVehicleCostsRow, error) {
	row := q.db.QueryRow(ctx, sumVehicleCosts, arg.VehicleID, arg.Since)
	var i SumVehicleCostsRow
	err := row.Scan(&i.MaintenanceCents, &i.ObligationsCents, &i.SeguroCents)
	return i, err
}
