package integration

import (
	"fmt"
	"net/http"
	"slices"
	"testing"
	"time"
)

func TestTimelineIncludesAbastecimentoWithoutDuplicatingOdometer(t *testing.T) {
	t.Parallel()
	e := newEnv(t)
	u := e.newUser()
	vehicleID := u.createVehicle(map[string]any{"current_mileage_km": 50_000})

	today := e.today().Format(time.DateOnly)
	maintenanceID := u.createRecord(vehicleID, 50_000, today)
	fillID := u.createAbastecimento(vehicleID, 50_650)
	_, generatedReadingID := e.odometerForAbastecimento(t, fillID)

	var page struct {
		Data []struct {
			ID         string `json:"id"`
			Kind       string `json:"kind"`
			OccurredOn string `json:"occurred_on"`
		} `json:"data"`
	}
	u.get("/v1/vehicles/" + vehicleID + "/timeline").
		expect(http.StatusOK).decode(&page)

	var fillIndex, maintenanceIndex int
	fillIndex, maintenanceIndex = -1, -1
	for i, entry := range page.Data {
		if entry.ID == generatedReadingID.String() {
			t.Fatalf("odometer reading %s generated by the fill appeared as its own timeline entry",
				generatedReadingID)
		}
		if entry.ID == fillID {
			if entry.Kind != "abastecimento" {
				t.Errorf("fill kind = %q, want abastecimento", entry.Kind)
			}
			fillIndex = i
		}
		if entry.ID == maintenanceID {
			maintenanceIndex = i
		}
	}
	if fillIndex < 0 {
		t.Fatal("timeline is missing the abastecimento")
	}
	if maintenanceIndex < 0 {
		t.Fatal("timeline is missing the maintenance record")
	}
	if fillIndex > maintenanceIndex {
		t.Errorf("abastecimento at index %d, maintenance at %d; newest-first wants the fill first",
			fillIndex, maintenanceIndex)
	}
}

func TestTimelineCursorCrossesAbastecimentoAndMaintenance(t *testing.T) {
	t.Parallel()
	e := newEnv(t)
	u := e.newUser()
	vehicleID := u.createVehicle(map[string]any{"current_mileage_km": 50_000})

	today := e.today().Format(time.DateOnly)
	maintenanceID := u.createRecord(vehicleID, 50_000, today)
	fillID := u.createAbastecimento(vehicleID, 50_650)

	seen := map[string]string{}
	cursor := ""
	for page := 0; ; page++ {
		if page > 20 {
			t.Fatal("pagination did not terminate")
		}

		url := fmt.Sprintf("/v1/vehicles/%s/timeline?limit=1", vehicleID)
		if cursor != "" {
			url += "&cursor=" + cursor
		}

		var body struct {
			Data []struct {
				ID   string `json:"id"`
				Kind string `json:"kind"`
			} `json:"data"`
			NextCursor *string `json:"next_cursor"`
		}
		u.get(url).expect(http.StatusOK).decode(&body)
		if len(body.Data) != 1 {
			t.Fatalf("page %d: got %d rows, want 1", page, len(body.Data))
		}

		entry := body.Data[0]
		if prev, dup := seen[entry.ID]; dup {
			t.Fatalf("id %s (%s) appeared twice; earlier kind %s", entry.ID, entry.Kind, prev)
		}
		seen[entry.ID] = entry.Kind

		if body.NextCursor == nil {
			break
		}
		cursor = *body.NextCursor
	}

	if seen[fillID] != "abastecimento" {
		t.Errorf("walked kinds for fill %s = %q, want abastecimento", fillID, seen[fillID])
	}
	if seen[maintenanceID] != "manutencao" {
		t.Errorf("walked kinds for record %s = %q, want manutencao", maintenanceID, seen[maintenanceID])
	}
}

func TestDashboardCostsKeepTrackedCentsWithoutFuel(t *testing.T) {
	t.Parallel()
	e := newEnv(t)
	u := e.newUser()
	vehicleID := u.createVehicle(map[string]any{"current_mileage_km": 50_000})

	today := e.today().Format(time.DateOnly)
	u.createRecord(vehicleID, 50_000, today)
	u.post("/v1/vehicles/"+vehicleID+"/obligations", map[string]any{
		"kind":              "ipva",
		"reference_year":    e.today().Year(),
		"due_on":            today,
		"amount_cents":      184_237,
		"paid_on":           today,
		"paid_amount_cents": 184_237,
	}).expect(http.StatusCreated)
	u.createSeguro(vehicleID)
	u.createAbastecimento(vehicleID, 50_650)

	var dashboard struct {
		Costs struct {
			MaintenanceCents  int64    `json:"maintenance_cents"`
			ObligationsCents  int64    `json:"obligations_cents"`
			SeguroCents       int64    `json:"seguro_cents"`
			TrackedCents      int64    `json:"tracked_cents"`
			TrackedCategories []string `json:"tracked_categories"`
			AbastecimentoCents int64   `json:"abastecimento_cents"`
			TotalCents        int64    `json:"total_cents"`
			Categories        []struct {
				Key   string `json:"key"`
				Label string `json:"label"`
				Cents int64  `json:"cents"`
			} `json:"categories"`
		} `json:"costs"`
	}
	u.get("/v1/vehicles/" + vehicleID + "/dashboard").
		expect(http.StatusOK).decode(&dashboard)

	costs := dashboard.Costs
	if costs.AbastecimentoCents != 20_000 {
		t.Errorf("abastecimento_cents = %d, want 20000", costs.AbastecimentoCents)
	}

	legacy := costs.MaintenanceCents + costs.ObligationsCents + costs.SeguroCents
	// Intentional: tracked_cents stays the pre-fuel total so a published app's three
	// bars still add up, and "Combustível ainda não entra nesta conta." keeps making sense.
	if costs.TrackedCents != legacy {
		t.Errorf("tracked_cents = %d, want %d (maintenance+obligations+seguro, no fuel)",
			costs.TrackedCents, legacy)
	}
	if costs.TrackedCents == costs.TotalCents && costs.AbastecimentoCents != 0 {
		t.Fatal("tracked_cents unexpectedly includes fuel")
	}
	if slices.Contains(costs.TrackedCategories, "abastecimento") {
		// Intentional: the published app hides the "fuel is missing" copy when this
		// list contains "abastecimento". Keep it off until that build is gone.
		t.Fatalf("tracked_categories = %v, must not contain abastecimento", costs.TrackedCategories)
	}

	var categorySum int64
	for _, category := range costs.Categories {
		categorySum += category.Cents
	}
	if costs.TotalCents != categorySum {
		t.Errorf("total_cents = %d, sum(categories) = %d", costs.TotalCents, categorySum)
	}
	if costs.TotalCents != legacy+costs.AbastecimentoCents {
		t.Errorf("total_cents = %d, want tracked+fuel %d",
			costs.TotalCents, legacy+costs.AbastecimentoCents)
	}
}

func TestDashboardLastAbastecimentoMatchesModule(t *testing.T) {
	t.Parallel()
	e := newEnv(t)
	u := e.newUser()
	vehicleID := u.createVehicle(map[string]any{"current_mileage_km": 50_000})

	empty := u.get("/v1/vehicles/" + vehicleID + "/dashboard").
		expect(http.StatusOK).json()
	if last, ok := empty["last_abastecimento"]; ok && last != nil {
		t.Fatalf("last_abastecimento = %#v, want absent or null on a vehicle with no fills", last)
	}

	u.createAbastecimento(vehicleID, 50_650)
	second := u.post("/v1/vehicles/"+vehicleID+"/abastecimentos", map[string]any{
		"mileage_km":       51_300,
		"volume_ml":        34_700,
		"total_cost_cents": 23_840,
		"fuel":             "gasolina",
		"full_tank":        true,
	}).expect(http.StatusCreated)
	secondID := second.id()

	fromModule := u.get("/v1/abastecimentos/" + secondID).expect(http.StatusOK).json()

	dashboard := u.get("/v1/vehicles/" + vehicleID + "/dashboard").
		expect(http.StatusOK).json()
	last, _ := dashboard["last_abastecimento"].(map[string]any)
	if last == nil {
		t.Fatal("last_abastecimento missing after recording fills")
	}
	if last["id"] != secondID {
		t.Errorf("last_abastecimento.id = %v, want %s", last["id"], secondID)
	}

	dashConsumption, _ := last["consumption"].(map[string]any)
	modConsumption, _ := fromModule["consumption"].(map[string]any)
	if fmt.Sprint(dashConsumption) != fmt.Sprint(modConsumption) {
		t.Errorf("dashboard consumption = %#v, module = %#v", dashConsumption, modConsumption)
	}
	for _, field := range []string{"total_cost_cents", "volume_ml", "price_per_liter_cents", "fuel", "occurred_on"} {
		if fmt.Sprint(last[field]) != fmt.Sprint(fromModule[field]) {
			t.Errorf("last_abastecimento.%s = %#v, module = %#v", field, last[field], fromModule[field])
		}
	}

	var alerts struct {
		Data []struct {
			Kind string `json:"kind"`
		} `json:"data"`
	}
	u.get("/v1/vehicles/" + vehicleID + "/alerts").expect(http.StatusOK).decode(&alerts)
	for _, alert := range alerts.Data {
		if alert.Kind == "abastecimento" {
			t.Fatal("abastecimento appeared in /alerts")
		}
	}
}
